### ISSUE TITLE
Wrong reviews today and time

### ISSUE THREAD

**Issue by timo95** [ThoreBor/Anki_Leaderboard#1]
It says i did 320 cards in 42.7 minutes today, but it was 491 in 83 minutes.

![grafik](https://user-images.githubusercontent.com/24251362/78140154-d688eb80-7429-11ea-94e1-cb6ae648f33b.png)

**Comment by ThoreBor** [comment]
I also just noticed something similar with my stats. The fix I just uploaded to ankiweb resolved the problem for me. Please check if the new version fixes this for you as well.

**Comment by timo95** [comment]
Now it shows 337 in 52,7. Still not correct.

**Comment by ThoreBor** [comment]
Okay, I'll figure it out.

**Comment by ThoreBor** [comment]
I uploaded a new version now. The problem was probably that card that were reviewed more than once were ignored. Please let me know if this fixed the issue for you.

**Comment by timo95** [comment]
Yes, it works now!
