### ISSUE TITLE
Highlight own account name in the list

### ISSUE THREAD

**Issue by JakubFranek** [ThoreBor/Anki_Leaderboard#10]
Hey, good work, just a quick suggestion, it would be easier to find one's own position in the leaderboard if the line with our account name was highlighted somehow. I am 90% sure you already thought of this but just in case :)
Cheers

**Comment by Willz7** [comment]
Its already there in green

**Comment by JakubFranek** [comment]
Oh sorry I can see it now after restarting Anki again. Thanks.
