### ISSUE TITLE
Error - invalid token

### ISSUE THREAD

**Issue by RusabBaig** [ThoreBor/Anki_Leaderboard#101]
Error - invalid token
When I redownloaded the Leaderboard add-on in order to fix it, since it was showing my Streak to be 2 days which is actually 33 days according to the heatmap, this dialog box shows up

**Screenshots**

![Screenshot (5334)](https://user-images.githubusercontent.com/70503545/91686322-949bd700-eb7a-11ea-9dba-314352171bd4.png)

When I click on "Ok"
this shows up
![image](https://user-images.githubusercontent.com/70503545/91686417-ddec2680-eb7a-11ea-8522-3eae97f7e9d8.png)

But according to the heatmap, you can see my streak is for 33 days
![image](https://user-images.githubusercontent.com/70503545/91686509-0c6a0180-eb7b-11ea-8a07-81df40124f53.png)

**Info**
- Anki version (2.1.29)
- Leaderboard version (2.1.29)
- OS: (e.g. Windows 10)

**Comment by ThoreBor** [comment]
You should be able to login now. 
Redownloading the add-on won't fix your streak problem. Make sure that you set the start of the next day in Leaderboard>Config the same as in Ankis preferences (Tools>Preferences>Scheduling). Let me know if this doesn't fix the issue.

**Comment by RusabBaig** [comment]
Thanks it's fine now
