### ISSUE TITLE
[Feature request] New group needed

### ISSUE THREAD

**Issue by kinkeymonkey161** [ThoreBor/Anki_Leaderboard#102]
Thanks a lot for creating this awesome add-on.
Can we have a new group named 'Indian Medical Server'. We are having weekly challenges kinda thing to make everyone keep up with their Anki reviews.So it'd be nice to have this group where we can check them all.
And you have mentioned about the [league update](https://github.com/ThoreBor/Anki_Leaderboard/issues/93#issuecomment-658318460). It'd be of great help if you release them in near future.

**Comment by ThoreBor** [comment]
How urgent is this? I'm going to release v1.6.0 soon (the 'league update'). With this update, you'll also be able to create/request new groups from the config. I'm currently quite busy, but I hope that I can release it in two or three weeks. Can you wait till then? If not let me know and I'll see what I can do.

**Comment by kinkeymonkey161** [comment]
Take your time, it isn't urgent. We'll wait for the update to get released.
