### ISSUE TITLE
[Feature Request] Sorting function and/or holistic ranking

### ISSUE THREAD

**Issue by itsbeenaminute1** [ThoreBor/Anki_Leaderboard#103]
It would be nice to be able to see ranking for more than just reviews by using a sorting function for each tab. And also maybe make a primary holistic ranking system which somehow accounts for all factors combined (reviews, total reviews past 31 days, etc...)

Anyway thanks for a very motivating add-on!

**Comment by ThoreBor** [comment]
You can sort by anything you want. Just click on the header of the column. And you can also set the default in the config. Or do you mean something else? 
In the next update there will also be a leagues tab. Users there will be ranked by xp (calculated based on time, reviews and retention). I explained it in #100.

**Comment by itsbeenaminute1** [comment]
Well in that case, I should mention the sorting function is not working for me. I click on a column header and it highlights the box, but does not sort the ranking based on that column.

**Comment by ThoreBor** [comment]
Did you enable auto-refresh in the config? If you did, sorting is disabled.

**Comment by itsbeenaminute1** [comment]
Oh I see how to sort now, thanks! However it would be cool if you could sort by clicking on the column rather than selecting it in the config, if possible. But this helps, thanks!

**Comment by ThoreBor** [comment]
Yes I agree, but this causes some bugs that I'm unable to fix atm.
