### ISSUE TITLE
Embed Daily Friend Reviews into Anki Homescreen

### ISSUE THREAD

**Issue by brianfogarty** [ThoreBor/Anki_Leaderboard#104]
It would be really cool to embed the friend's list into the home screen of Anki (not global list, just added friends). So immediately when I open Anki, next to my heatmap, I can see how many reviews each one of my added friends did that day and how I compare, for extra motivation.

**Comment by ThoreBor** [comment]
I like the idea. I don't know how to do that yet, but I think I can figure it out. I'm planning to release a new update in October. Not sure if I can get it done by then, but I'll keep it in mind.

**Comment by ThoreBor** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/40232329/94031605-57181b80-fdbf-11ea-8f57-cb7e58c7bc26.png)

**Comment by brianfogarty** [comment]
Yes!! That would be awesome!! That looks so good. Just of the added friends though - not globally/nationally 

Sent from my iPhone

On Sep 23, 2020, at 10:08, Thore <notifications@github.com> wrote:

﻿
Something like this?

**Comment by ThoreBor** [comment]
Great! I just went ahead and made it customizable, so you can choose which leaderboard appears on the homescreen (and it can of course also be disabled completely). Plus it automatically updates when you finish a deck.
I'll include it in the next update.

**Comment by brianfogarty** [comment]
You’re awesome. 

When are you expecting to release the next update? Early Oct? 

Sent from my iPhone

On Sep 23, 2020, at 10:53, Thore <notifications@github.com> wrote:

﻿
Great! I just went ahead and made it customizable, so you can choose which leaderboard appears on the homescreen (and it can of course also be disabled completely). Plus it automatically updates when you finish a deck.
I'll include it in the next update.
