### ISSUE TITLE
leaderboard not on home screen

### ISSUE THREAD

**Issue by sc00bacat** [ThoreBor/Anki_Leaderboard#105]
**Describe the bug**
When "show leaderboard on homescreen" checked in settings, the column headers appear but the leaderboard users do not appear

**Screenshots**
![Screen Shot 2020-10-05 at 10 53 03 AM](https://user-images.githubusercontent.com/63348779/95095388-fc54bd00-06f8-11eb-8241-7fa81e360785.png)

**Info**
- Anki version 2.1.26
- Leaderboard version 1.6.0
- If relevant Add-on config info (start of new day, autoscrolling enabled etc.)
- OS: macOS mojave

**Comment by ThoreBor** [comment]
What's your default leaderboard?

**Comment by sc00bacat** [comment]
This occurs when my default is Country

**Comment by sc00bacat** [comment]
works fine with Global

**Comment by ThoreBor** [comment]
Okay, I think I know what the issue is. In some cases it could also affect groups if I'm right. I'll fix it in the next update. Just btw. leagues also don't work at the moment.

**Comment by ThoreBor** [comment]
Just as suspected. Fixed it!

**Comment by sc00bacat** [comment]
Awesome, I appreciate it! Love this add on, thanks for all your work on it
