### ISSUE TITLE
Cant see friends under friends list, but can see them in league boards

### ISSUE THREAD

**Issue by jojobear1999** [ThoreBor/Anki_Leaderboard#106]
When I open up my friends list, it is empty. However, If I scroll down on the leagues page, I can see my friends' usernames. To further clarify my friends list is completely empty every time I check it. However, I can see my 2 friends on the league page highlighted in blue.

I have the latest versions of anki and the leaderboard add on.

Thanks for your work so far!

**Comment by ThoreBor** [comment]
Your friends only show up on the leaderboards (except leagues) when they synced the same day as you. On the leagues' leaderboard, they only have to sync once per league (and also have to be in the same league as you). Could this be the issue? You can check their last sync time here: https://ankileaderboard.pythonanywhere.com/user/their_username
