### ISSUE TITLE
Message to a friend

### ISSUE THREAD

**Issue by Flippo008** [ThoreBor/Anki_Leaderboard#107]
Hello,

I just discovered Anki Leaderboards and found someone who goes to the same school as I do. I immediately added his as friend hoping I could send him a message, but could not find a way how to do so. Am I missing something or this feature is not available yes? Can it be added?

Thanks in advance.

**Comment by ThoreBor** [comment]
Hi, for now you can't send messages to other users (see #86). I might add it in the future, but it's not a priority. 
In the meantime, you can use the status message to link to your social media if you want other users to be able to contact you.

**Comment by Flippo008** [comment]
Oh, never mind, thank you for the advice, I might use it. :) I really like your addon anyway, good job.
