### ISSUE TITLE
Can you make a favor? 

### ISSUE THREAD

**Issue by NameLessGO** [ThoreBor/Anki_Leaderboard#108]
Hi, i was the owner of the nickname NameLessGO but when i restarted my anki, i lost the file containing ownership of the account(NameLessGO), so now im using the NameLess account
Could you delete the older one so that i can replace it?
i don't have actually proof to show you that i am the owner, so it is ok if you don't belive me.

**Comment by ThoreBor** [comment]
You should now be able to use NameLessGO again. You can either delete it or continue using it.
