### ISSUE TITLE
Help Fixing this

### ISSUE THREAD

**Issue by noseyposey17** [ThoreBor/Anki_Leaderboard#111]
---------------------------
Anki version 2.1.15
Windows 8
---------------------------
An add-on you installed failed to load. If problems persist, please go to the Tools>Add-ons menu, and disable or delete the add-on.

When loading 'Leaderboard':
Traceback (most recent call last):
  File "aqt\addons.py", line 80, in loadAddons
  File "C:\Users\jessica\AppData\Roaming\Anki2\addons21\41708974\__init__.py", line 5, in <module>
    from aqt import gui_hooks
ImportError: cannot import name 'gui_hooks'

**Comment by ThoreBor** [comment]
Okay, thanks for letting me know. I know what the issue is and I'll fix it in the next update.
