### ISSUE TITLE
I am in a group of red usernames and I don't know why

### ISSUE THREAD

**Issue by itsbeenaminute1** [ThoreBor/Anki_Leaderboard#113]
I don't know if this red highlight is reserved for cheaters but I have been doing my cards honestly and haven't used any shortcuts to boost my reviews or falsify my retention. I am not sure why I am in this group.  This morning I was in 1st place in the Gamma league.

Also, from what I saw last time I checked last night I was in 3rd place in the league (futurepathdr), and I am not sure if that should have put me in a different league (not to mention a user above me who had >99% retention which seems suspicious). 

EDIT: Now I'm seeing I am out of red but all of my reviews and minutes have disappeared and reset. I am not sure why I lost all of my progress.

**Comment by ThoreBor** [comment]
In Leaderboard>Config>About you'll find a short explanation of how leagues work. Leagues reset every two weeks. The top 20% (green) will get to the next league and the bottom 20% (red) will drop down a league. Hope this helps.

**Comment by itsbeenaminute1** [comment]
> In Leaderboard>Config>About you'll find a short explanation of how leagues work. Leagues reset every two weeks. The top 20% (green) will get to the next league and the bottom 20% (red) will drop down a league. Hope this helps.

I am saying I was top 20% last league, I was actually third place of the delta league as of last night. This morning I started the Gamma league in 1st place. Then a few minutes later I checked and I was in the red. I am wondering why I lost my position and all of my progress (my XP reset to 0 today!!!).

**Comment by ThoreBor** [comment]
The top 20% of the delta league are now in the gamma league (one league up). The next season started today at 0:00 UTC.  The stats will be calculated based on the reviews etc. you'll do from this point on. You might see some users with their old score, but this will be reset as soon as they restart anki (this was a mistake on my part). Everything should probably look normal tomorrow.

**Comment by itsbeenaminute1** [comment]
Got it thanks for the explanation!
