### ISSUE TITLE
Server Error (500)

### ISSUE THREAD

**Issue by ArcticClaw** [ThoreBor/Anki_Leaderboard#115]
**Describe the bug**
Two separate devices, accounts, and users with the same 'Server Error (500)' when opening the leaderboard and syncing. Have tried disabling all other add-ons but the error persists. Username does not appear on any lists.

**Screenshots**
N/A

**Steps to reproduce bug**
- Open Leaderboard
- Sync and update

**Info**
- Anki version v2.1.35
- Leaderboard version v1.6.0
- If relevant Add-on config info - tested without Add-ons but error persists
- OS: Windows 10

**Additional context**
N/A

**Comment by EduardoMaiaUFMG** [comment]
Same for me.

**Comment by ThoreBor** [comment]
Thanks for letting me know. It should be fixed now.

**Comment by ArcticClaw** [comment]
Working perfectly now! Thanks again for the great add-on.
