### ISSUE TITLE
Server Error (500) when I try to join a group.

### ISSUE THREAD

**Issue by talenelat-elin** [ThoreBor/Anki_Leaderboard#119]
**Describe the bug**
When I try to join a group, any open group without a password. It shows a popup window saying Server Error (500)

**Screenshots**
![image](https://user-images.githubusercontent.com/71895835/97157290-e8532700-179d-11eb-9452-c17add7c309a.png)

**Steps to reproduce bug**
Install addon
Create username.
Try to join an existing group.

**Info**
- Anki version: 2.1.33
- Leaderboard version 1.6.1
- If relevant Add-on config info (start of new day, autoscrolling enabled etc.)
- OS: Windows 10

**Additional context**
If I try to add certain group, it displays a popup saying incorrect authentication token. (I'm assuming these groups require a password)

**Comment by ThoreBor** [comment]
Sorry, I somehow completely overlooked this issue. Do you still have this problem?
