### ISSUE TITLE
Suggestion: Show the rank of the person seeing the leaderboard when leaderboard is open

### ISSUE THREAD

**Issue by vilut** [ThoreBor/Anki_Leaderboard#12]
I am not sure if someone that is ranked 200 wants to know the name and streak length of all 199 people above them. Maybe have an option to see the top 10 and then its own position? Or better, something like showing the first 25 and the rank of the viewer and a bottom below named "see more" to see 25 more people and so on up until the end of the leaderboard.

**Comment by ThoreBor** [comment]
Thanks for the suggestion. I'll keep it in mind for future updates.

**Comment by khonkhortisan** [comment]
In Fold-it the leaderboard auto-scrolls so you're in the center of the view, with people above and below you.

**Comment by ThoreBor** [comment]
In the next update you can enable the option to autoscroll to your username.
