### ISSUE TITLE
Home screen shows wrong number of users

### ISSUE THREAD

**Issue by RobethX** [ThoreBor/Anki_Leaderboard#120]
**Describe the bug**

On the home screen leaderboard, if *Focus on users* is **enabled** and the *Maximum number of users on home screen leaderboard* setting is set to an **odd number**, it displays 1 less than it should.

**Screenshots**

Max users on home screen leaderboard set to 5 (shows 4):
![Screenshot from 2020-10-27 01-36-38](https://user-images.githubusercontent.com/1686473/97261438-39423a00-17f5-11eb-800a-fc5837db65b8.png)
Max users on home screen leaderboard set to 4 (shows 4):
![Screenshot from 2020-10-27 01-36-50](https://user-images.githubusercontent.com/1686473/97261452-419a7500-17f5-11eb-957e-ed54e54ca566.png)
Max users on home screen leaderboard set to 3 (shows 2):
![Screenshot from 2020-10-27 01-37-14](https://user-images.githubusercontent.com/1686473/97261458-43fccf00-17f5-11eb-8379-458eafe46239.png)

**Steps to reproduce bug**

In the *Settings* tab of the *Leaderboard Config* window:
1.  Enable the *Show leaderboard on home screen*
2. Enable *Focus on user*
3. Set the *Maximum number of users on home screen leaderboard* to an odd number greater than 1.

**Info**

- Anki version v.2.1.35
- Leaderboard version v1.6.1
- OS: Ubuntu 18.04 LTS

**Additional context**

Likely caused by a rounding issue on [this line of code](https://github.com/ThoreBor/Anki_Leaderboard/blob/8621d3d0eed3bbe7aa8ab790af9108e0d2377dbb/lb_on_homescreen.py#L106l).

:heart:

**Comment by ThoreBor** [comment]
Thanks for letting me know. It really looks like it's just a rounding issue, so I'll probably fix it in the next update.
