### ISSUE TITLE
Getting a 500 error when trying to join any group

### ISSUE THREAD

**Issue by Ankizumab** [ThoreBor/Anki_Leaderboard#121]
**Describe the bug**
Using Anki, Version 2.1.35 (84dcaa86), getting a Server Error (500) when trying to join a group under the Leaderboard Config -> Group tab. I've attempted to join multiple groups to see if the error goes away, and I receive the same error regardless of the group I a am attempting to join. I am not using a password to join any of the groups. 

**Screenshots**

![image](https://user-images.githubusercontent.com/73597259/97445885-1eaab680-1904-11eb-90d6-43f9edbfd667.png)

**Steps to reproduce bug**
Go to Leaderboard Config menu, Group tab, select a group from the dropdown menu, click "Join Group" button.

**Info**
- Anki version 2.1.35
- Leaderboard version 1.6.1
- Add-on config info: United States
- OS: Windows 10

**Comment by ThoreBor** [comment]
Thanks for letting me know. The new update I just released should fix this issue.
