### ISSUE TITLE
Anki freezing for seconds while Leaderboard active on home screen (Ubuntu)

### ISSUE THREAD

**Issue by MaximeLeFloch** [ThoreBor/Anki_Leaderboard#124]
First of all, thank you for your add-on, it's really great work.

**Describe the bug**
As soon as I activate the home screening option in the config, everything action I'm doing in Ankis menu is freezing for a few seconds. This could be for example changing other options in the add-on config or just expanding a deck in the home screen.

As soon as I unchecked the home screen option, the software recovers his normal speed.

**Info**
- Anki version 2.1.35
- Leaderboard version 1.6.2
- Other Add-on: Advanced review bottom bar, Image occlusion enhanced for anki 21 alpha, More decks stats and time left, Puppy reinforcement, review heatmap
- OS: Ubuntu 20.04.1 LTS

**Comment by ThoreBor** [comment]
Yes, I'm aware of that. It's because the leaderboard requests data too frequently. I'll fix it in the next update.
