### ISSUE TITLE
Ability to duplicate usernames

### ISSUE THREAD

**Issue by Bob132639** [ThoreBor/Anki_Leaderboard#125]
"MSA yatyatmui" and "yatyatmui" are presumably the same person, but they now occupy the 1st and 2nd positions in Delta league as independent people.

**Comment by ThoreBor** [comment]
It's probably the same person, but it looks like it's from different Anki accounts. Some people asked if it's possible to combine the data of two Anki profiles. It's not, so that might be what happened here (see for example #109).
