### ISSUE TITLE
Streak not accurate???

### ISSUE THREAD

**Issue by DoctorToBeIn23** [ThoreBor/Anki_Leaderboard#126]
I am updated to the newest version, I haven't checked in awhile but something has changed because my streak was correct before but now it is not accurate. My current streak is 553 but it is showing up as 158.

**Comment by ThoreBor** [comment]
Yes, there seems to be a problem. Probably because of different timezones. Could you check if [this]( https://drive.google.com/file/d/1jo-0G2YPmLT-LNYavdVh4Y_R2-usnduN/view?usp=sharing) fixes the problem? Just download the .ankiaddon file and open it to install it.

**Comment by ZanDatsu** [comment]
I'm having the same issue and the above .ankiaddon file hasn't seemed to fix it.

**Comment by ThoreBor** [comment]
Okay, thanks for letting me know. I'll try to fix it as fast as possible. Maybe @SmallFluffyIPA  has an idea?

**Comment by ThoreBor** [comment]
Sorry, I just have to make sure: Did you restart Anki after you installed the add-on?

**Comment by ZanDatsu** [comment]
I did yes. I actually uninstalled the addon entirely and reinstalled the one above again just now and the streak count has dropped even further than what it was before.

**Comment by ThoreBor** [comment]
Alright, thanks.

**Comment by ThoreBor** [comment]
If you want to, you could upload your collection so I can take a closer look.

**Comment by ThoreBor** [comment]
Could someone try if [this](https://drive.google.com/file/d/1NXiZ-qDHD71HANnGnYJbdiYJMyuh_P9f/view?usp=sharing) fixes the issue?

**Comment by DoctorToBeIn23** [comment]
> Yes, there seems to be a problem. Probably because of different timezones. Could you check if [this](https://drive.google.com/file/d/1jo-0G2YPmLT-LNYavdVh4Y_R2-usnduN/view?usp=sharing) fixes the problem? Just download the .ankiaddon file and open it to install it.

This worked for me

**Comment by ThoreBor** [comment]
Thank you! I now heard from two people, that the first solution works for them. I don't really understand why it's not working for you @ZanDatsu.  Does the other one work? In which timezone are you and when is the start of your new day (Leaderboard>Config>Settings>)?

**Comment by ThoreBor** [comment]
I just released a new version that hopefully fixes the problem. I'm going to keep this issue open though and pin it. In case someone still has this problem with v1.6.3.1, please report it here.

**Comment by vilut** [comment]
I think I am having a rather similar problem. But instead of being my streak, it is my "Days learned" that are not ok. I currently have a streak of 12 days and my league has started a couple days ago, so it it's impossible I have less than 100%. What's the problem here and how can I fix it?

**Comment by ThoreBor** [comment]
Unlike the normal streak on the leaderboards, days in "days studied" only count if you studied for at least 10 minutes. Could this be the problem?

**Comment by vilut** [comment]
Yes, most definitely yes. I am studying a language, so most of my cards are a single word and its translation, which means I can easily revise 10-15 cards a minute, so sometimes I don't study more than 10 minutes.
Is there any reason for this? If it is to avoid people to study just 1 card to keep the streak, it can easily become unfair to people who can study simple cards quickly.
Thank you for your reply anyway.

**Comment by ThoreBor** [comment]
Hi, @vilut. Sorry for the late reply.  The thought process behind it is explained in #122. The basic idea is that I don't want people in leagues to just do one review and get credit for studying that day. 10 minutes a day might be a bit high. I could reduce it, or instead have a threshold of 50 cards or something.

**Comment by vilut** [comment]
Hey @ThoreBor. I think your idea makes sense. I think 10 minutes is not much actually. It is just that it depends on what the student is studying. Maybe a language can be quicker, medicine as a lot of people are using Anki for may take more time per card. If you are not confident 50 cards is the right amount, maybe you could considering calculating how many cards a user is studying per ten minutes and use that average as a minimum amount for studying? In the end, to calculate the streak it could be something like 10 minutes or X cards.

**Comment by ThoreBor** [comment]
I think it should be the same for all users. I'll probably either decrease the max time or switch to something like 50 or so cards which should probably be fair for most people in the next update.

**Comment by Bob132639** [comment]
@vilut 

Keep in mind language learners already have an advantage for the same reason (More cards in shorter time span and usually more accuracy means higher XP than someone identical in medicine or some other subject).

But I do like the idea of 10 minutes OR 75 cards (that's about 5 minutes at your fast average). Any lower than that and it should just be on you to make more cards on a daily basis. I think 75 is low enough not to have to make new cards too often to hit the threshold. 

Just my thoughts... as I get relegated back to Delta league 😂

**Comment by DoctorToBeIn23** [comment]
Maybe just make new cards learned less of exp? I think Med students actually uber the advantage of learning 80-120 new a day. But idk how many new words language learners strive for.

**Comment by vilut** [comment]
@Bob132639 

More cards in shorter time span is definitely an advantage. But that advantage has been taken cared of as the XP calculation favors more time spent on the app studying over the number of cards. So if I revise faster, I spend less time on the app. We could argue about the factors of XP calculation being fair, but that's another question. As a language learner, I believe it is unfair, med students will say otherwise, so let's keep it that way ahah


@DoctorToBeIn23
I would say that would depend on language similarity to native language (more similarity, it is easier to keep up with dozens of new words per day; less similarity leads to more errors and reviews cards will build up quite fast; also, there's no point in studying 100 words per day if you are not getting their meanings right) and the amount of time one has to spend learning a language. Personally, I aim at 20 cards/day because I only add cards with unknown words I found in books/articles. So, for me to add a word, I have to read an article, find a word I don't know the meaning of, check its meaning and then add it to Anki. A language learner doesn't just study in Anki (as I am sure a med student doesn't just study on Anki, but it is just to give you an idea).

**Comment by Bob132639** [comment]
@vilut 

The break even point between Time Spent and Cards Studied is 1 card every 20 seconds (I think). More than that and your cards studied are worth more than your time spend. Obviously studying 15 cards a minute is quite a bit more XP from cards than time. 

I mean this is the competitive league section of Leaderboard where studying more means doing better. At the end of the day, anyone studying less than 30 minutes a day isn't getting out of Delta League anyway (and definitely not the higher leagues) so why tailor to those people when setting the daily thresholds? (We are 2.5 days into this season and there's only one person in a promotion spot with less than 40 minutes per day, no where near the 10 minute mark).

**Comment by vilut** [comment]
@Bob132639 
Yeah you are correct. Maybe if more leagues are created, the 10 min mark would make a bigger difference.
