### ISSUE TITLE
XP isn't calculating properly

### ISSUE THREAD

**Issue by Bob132639** [ThoreBor/Anki_Leaderboard#128]
I think the retention % bracket is being set at 0 for everyone in the if else function because their scores are only reflecting time spent and day % as of right now.

**Comment by ThoreBor** [comment]
Oh, thanks. Should be fixed now!

**Comment by Bob132639** [comment]
Yeah, it's fixed, but there's something else going on with the formula. I haven't looked at the numbers but they don't look right for some people.

**Comment by Bob132639** [comment]
So I figured out what the issue is. When you use the percentage for the "Days Studied %" as a whole number, it's fine because it's applied across the entire equation, but when you use the percentage for "Retention %" Bracket) as a whole number instead of the decimal equivalent, you are making the reviews side of the equation 100x bigger than the time spent side of the equation. 

Example:
30,665,900 = 100*((76.5*6)+(2*1531*100)
28,928,220 = 100*((213.7*6)+(2*1440*100)

Clearly the second person should be getting a much bigger score and it's fixed if you do this instead:

352,100 = 100*((76.5*6*1)+(2*1531*1)
416,220 = 100*((213.7*6*1)+(2*1440*1)

OR

35,210,000 = 100*((76.5*6*100)+(2*1531*100)
41,622,000 = 100*((213.7*6*100)+(2*1440*100)

OR

3,521 = 1*((76.5*6*1)+(2*1531*1)
4,162 = 1*((213.7*6*1)+(2*1440*1)

You can pick whatever scaled version you want. The 1s can obviously be omitted from the first brackets (time) but not from reviews or days studied.

**Comment by Bob132639** [comment]
Oh, and Hugh and HughLeDuc in Delta is clearly same person with duplicated information (as opposed to the same person restarting with a new profile and managing to get to the top twice). It's probably not that big of a deal but just so you are aware.

**Comment by ThoreBor** [comment]
Thanks you're right. I think I'd go with this:

> 352,100 = 100x((76.5x6x1)+(2x1531x1))
416,220 = 100x((213.7x6x1)+(2x1440x1))

But just to make sure, you want the multiplier in the time part to always be 1, right? That's not the retention bracket only to compensate for the retention bracket in the review part of the formula. Am I understanding this correctly?

**Comment by ThoreBor** [comment]
So if the retention would be 75% for example it would be:
`xp = 100x((213.7x6x1)+(2x1440x0.85))`

**Comment by Bob132639** [comment]
Yeah, that's perfect. 

So I have another issue where my "Days Studied %" is showing as 50% over the last 2 days even though I did reviews yesterday and reviews today (the reviews today are still changing my XP so it's not a lack of updating). I closed and reopened ANKI and synced.

**Comment by Bob132639** [comment]
Not sure if you need my username for this cus I can't really get any additional information.

**Comment by ThoreBor** [comment]
Alright, I fixed it. I probably should reset everyone to make it fair. Otherwise, users that don't sync for the rest of the season would score better than they should. 
Thanks for your help.

**Comment by Bob132639** [comment]
Yeah, works, although I was a little confused when I saw my number had gone down by 80% and no one else had. Definitely need that reset, haha.

**Comment by ThoreBor** [comment]
Yes, I was also worried :D Just reset it for everyone and also sent a notification 👍
