### ISSUE TITLE
Leaderboard not working

### ISSUE THREAD

**Issue by jeremyalexx** [ThoreBor/Anki_Leaderboard#131]
Hi there, 

The leaderboard is not working on my Windows PC - it does work on my Macbook Pro.

**Computer Specs:**
Processor	Intel(R) Core(TM) i7-9700KF CPU @ 3.60GHz   3.60 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor

**Anki Specs:**
Version 2.1.34 (8af8f565)
Python 3.8.0 Qt 5.15.1 PyQt 5.15.1

**The error is as below:**

Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.34 (8af8f565) Python 3.8.0 Qt 5.15.1 PyQt 5.15.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-01-22 18:58:17

Caught exception:
Traceback (most recent call last):
  File "C:\Users\jerem\AppData\Roaming\Anki2\addons21\41708974\__init__.py", line 26, in Main
    mw.leaderboard = start_main(season_start, season_end, current_season)
  File "C:\Users\jerem\AppData\Roaming\Anki2\addons21\41708974\Leaderboard.py", line 46, in __init__
    self.setupUI()
  File "C:\Users\jerem\AppData\Roaming\Anki2\addons21\41708974\Leaderboard.py", line 95, in setupUI
    self.load_leaderboard()
  File "C:\Users\jerem\AppData\Roaming\Anki2\addons21\41708974\Leaderboard.py", line 285, in load_leaderboard
    self.dialog.Custom_Leaderboard.item(custom_counter-1, j).setBackground(QtGui.QColor(colors['USER_COLOR']))
AttributeError: 'NoneType' object has no attribute 'setBackground'

Thank you for your assistance.

**Comment by ThoreBor** [comment]
Looks like it has to do something with the groups' tab. Are you in a group? Did you recently join a group or switched groups?

**Comment by jeremyalexx** [comment]
I think I am in the MedSchoolAnki good but I did not join it recently.

**Comment by ThoreBor** [comment]
Could you try joining another group and see if that changes anything?

**Comment by jeremyalexx** [comment]
Hi ThoreBoc, it seems to be working now. I didn't change anything either... who knows! Thank you for your help.
