### ISSUE TITLE
Have several groups

### ISSUE THREAD

**Issue by Osarel36** [ThoreBor/Anki_Leaderboard#133]
Hi, I was wondering if it was possible to have several groups? I'm in a very small French group, there are few active people but I like to watch their stats because I communicate with them sometimes on a forum. But when there is little activity, I like to go to another group open to everyone, the concern is that I have to go in my settings to change group and I disappear from the first group. 
So I was wondering if it was possible to develop something to be able to make the several groups we entered appear? 

It's just a suggestion, if not thank you again for this add-on, it's really great.

**Comment by ThoreBor** [comment]
Hi, sorry for the late reply.
Thanks for the suggestion. I think it's a good idea to be able to join multiple groups. I'm not sure how I would do it, but I'll add it to my to-do list. I don't have much time to work on the add-on at the moment, so it might take a while.

**Comment by Osarel36** [comment]
Thank you, it's nice that you take my suggestion into account. Take your time. Thanks again for this add-on that keeps me motivated in my learning.

**Comment by ThoreBor** [comment]
This will be included in the next update, which I'll hopefully be able to release soon.
