### ISSUE TITLE
Report-Function for League

### ISSUE THREAD

**Issue by jiaan87** [ThoreBor/Anki_Leaderboard#134]
Please add a report button for the league. There are people cheating to be on the first place.
e.g. at the moment in the delta league did someone 32000 cards in 25 minutes..

**Comment by ThoreBor** [comment]
There will be a report function in the next update. Most of the code is already on GitHub, but I want to change a few other things before releasing it.
Thanks for letting me know

**Comment by jiaan87** [comment]
Thank you!
