### ISSUE TITLE
Leaderboard friends

### ISSUE THREAD

**Issue by YaraAEzz** [ThoreBor/Anki_Leaderboard#135]
I added a friend through Tools>add-ons>leaderboard>config>friends>add friend. And on that page the friend is added. But when I open the leaderboard itself, I cannot see their account. I tried removing them a couple of time and re-adding...nothing. I tried uninstalling the add-on and reinstalling...nothing. I am using Anki's latest version for macOS. Mind you that I was able to see my friend in the leaderboard before.

- Anki version (2.1.42)
- Leaderboard version (v1.6.3.1)
- If relevant Add-on config info (start of new day, autoscrolling enabled etc.)
- macOS: (v11.2.3 (20D91))

**Comment by ThoreBor** [comment]
Hi, you'll only see friends that synced on the same day as you. So if your friends didn't open the leaderboard today, you won't see them because there's no data. Could this be the problem?

**Comment by YaraAEzz** [comment]
We both open and sync daily. Still not able to see each other.

**Comment by ThoreBor** [comment]
Could you tell me your and your friend's username?

**Comment by YaraAEzz** [comment]
Mine is “Yara”. His is “Sphinx”. He tried using another username “Kanaka”, worked for a couple of days then disappeared again from leaderboard. Let me know if the problem could be troubleshot—either of his usernames is fine.

**Comment by ThoreBor** [comment]
The last time Sphinx was active was on March 14th and Kanaka on March 19th. I tried to add you as a friend and I can see you just fine. If your friend could sync daily again I could see if I can add him as well.
