### ISSUE TITLE
Error viewing leaderboard and adding groups

### ISSUE THREAD

**Issue by ondansetran** [ThoreBor/Anki_Leaderboard#136]
**Describe the bug**
I deleted the leaderboard today to try to make a new account, downloaded it again, logged back in, joined my group, and it worked for a little. I think I went to sync on the leaderboard and the issue began. I wasn't able to sync or view the leaderboard and got the error below (I). I tried to delete the leaderboard and redo everything, but when I try to view the leaderboard I get the previous error. Additionally, when I try to join a group, I get the other error notice below (II).

**Screenshots**
I. <img width="422" alt="Screen Shot 2021-03-17 at 9 41 55 PM" src="https://user-images.githubusercontent.com/80868664/111566168-b2bdd300-876a-11eb-967d-7fcdd925ac03.png">
II. <img width="379" alt="Screen Shot 2021-03-17 at 9 42 40 PM" src="https://user-images.githubusercontent.com/80868664/111566205-c23d1c00-876a-11eb-972f-d4481fe62e3f.png">

**Steps to reproduce bug**
1. Delete leaderboard
2. Re-add leaderboard
3. Sync leaderboard
4. Close out and open anki
5. Error occurs when reopening and trying to view and/or sync

**Info**
- Anki version: 2.1.35 (Help>About; e.g. 2.1.24)
- Leaderboard version: 1.6.3.1 (Leaderboard>Config>About tab; e.g. v.1.4.4)
- If relevant Add-on config info (start of new day, autoscrolling enabled etc.)
- OS: (e.g. Windows 10)

**Additional context**

**Comment by ThoreBor** [comment]
Thanks for letting me know. If you tell me your username, I can probably fix it for you.

**Comment by ondansetran** [comment]
It does, thanks!
