### ISSUE TITLE
Forgot Group Password

### ISSUE THREAD

**Issue by atlas-tesla** [ThoreBor/Anki_Leaderboard#137]
I created a group a few days ago, but I forgot the password in that short time (whoops). How do I change the password or somehow gain access to the group again?

**Comment by ThoreBor** [comment]
What's the name of the group?

**Comment by atlas-tesla** [comment]
LongSOM 2024


________________________________

**Comment by ThoreBor** [comment]
Do you mean LSOM 2024?

**Comment by atlas-tesla** [comment]
Oh yes, I’m so sorry about that - I’m trying to create a group for my medical school class but I completely forgot the password I used. I should’ve written it down


________________________________

**Comment by ThoreBor** [comment]
Okay you can set a new password now
