### ISSUE TITLE
Rescheduling a card makes that this card is count like reviewed

### ISSUE THREAD

**Issue by oskaurypoker** [ThoreBor/Anki_Leaderboard#138]
**Describe the bug**
When you reschedule a card, that card count like reviewed, although you have not reviewed actually.

**Screenshots**

**Steps to reproduce bug**
In this screenshot you can see that I have not reviewed a single card today:
![image](https://user-images.githubusercontent.com/39686363/111913250-a922bc80-8a43-11eb-90a2-820e27578497.png)

In the next screenshot, you can see that in the Heatmap Review add-on I "have reviewed" 3,569 fc:
![image](https://user-images.githubusercontent.com/39686363/111913292-e0916900-8a43-11eb-8603-a8b943b2456d.png)

In this screenshot, in the Global Leaderboard, you can see that exactly amount of fc "reviewed":
![image](https://user-images.githubusercontent.com/39686363/111913398-55fd3980-8a44-11eb-9f73-f4bc77c46a6d.png)

**Info**
- Anki version 2.1.38
- Leaderboard version 1.6.3.1
- Add-on config info:
![image](https://user-images.githubusercontent.com/39686363/111913475-a96f8780-8a44-11eb-8d68-a543cdad2a80.png)

- OS Windows 10

**Comment by ThoreBor** [comment]
Thanks for letting me know. I wasn't aware of that. I already found what the issue was and fixed it. I still have to change some other stuff, but I'll try to release an update with that fix as soon as possible.
