### ISSUE TITLE
Login with email and password rather than the username (meta.json file)

### ISSUE THREAD

**Issue by NameLessGO** [ThoreBor/Anki_Leaderboard#141]
Lost the meta.json file because had to reset the pc (NameLessGO)
![image](https://user-images.githubusercontent.com/66227691/116818619-5bb56700-ab3a-11eb-9b80-19c2ebe8fb3a.png)

Create an account with email and password like the Anki Killstreak add-on 
![image](https://user-images.githubusercontent.com/66227691/116818717-bfd82b00-ab3a-11eb-9f34-7c57df384ec8.png)

**Comment by ThoreBor** [comment]
I think I've found a secure way of doing this by using firebase. So in the next update, you can finally sign-up and log in with email and password
