### ISSUE TITLE
Leaderboard 401 error

### ISSUE THREAD

**Issue by spyntt** [ThoreBor/Anki_Leaderboard#147]
i recently downloaded anki to a new device and when i try to join the leaderboard groups, it shows the 401 error (image). i migrated all the leaderboard files between devices, and re-installing the add-on. it didn't work. 
what do i do?

![image](https://user-images.githubusercontent.com/81307385/127473503-720825b4-b184-4e26-83ce-b7dd6efd1c77.png)

**Comment by ThoreBor** [comment]
Will resolve this via email
