### ISSUE TITLE
Incorrect streak reported

### ISSUE THREAD

**Issue by jesteadham** [ThoreBor/Anki_Leaderboard#148]
**Describe the bug**
After a 1,500 day streak, a screen pops up that gives an incorrect streak/spelling. The streak on the leaderboard itself is correct. 

**Screens
![Here is a screenshot](https://user-images.githubusercontent.com/71572229/127980821-0c19b4dc-b948-45e5-b6b3-f032aab64139.png)

**Steps to reproduce bug**
N/A

**Info**
- Anki version: 2.1.44
- Leaderboard version: v1.7.0
- If relevant Add-on config info (start of new day, autoscrolling enabled etc.)
- OS: Ubuntu 20.04.2 LTS

**Comment by ThoreBor** [comment]
Thanks for letting me know. That's very odd. Normally there's also supposed to be a confetti gif in the background. Did you see that? I'll try to reproduce it and fix it.

**Comment by jesteadham** [comment]
Nope. Just what you see above. Resizing the window didn't seem to change anything either. 

If it makes a difference, these are the other add-ons I have installed:

- anki simuilator
- awesomeTTS
- Review Heatmap
- Snytax Highlighting for Code

**Comment by ThoreBor** [comment]
Okay, thanks. I'll look into it, but I have no idea why this would happen

**Comment by jesteadham** [comment]
Next week or so I can try to dig around on my end to see if it's something unique to me. This is outside any of my areas of expertise, but any chance it's like an html container overflow type of error? Like there's not enough space to contain both the "1" and "k"?

**Comment by ThoreBor** [comment]
Yes, I was also thinking that it's maybe a cropping issue, but I'm not sure.

**Comment by ThoreBor** [comment]
I think I just found out why this wasn't working for you. It should be fine after the next update.
