### ISSUE TITLE
Color contrast is bad.

### ISSUE THREAD

**Issue by Nanco300** [ThoreBor/Anki_Leaderboard#150]
![image](https://user-images.githubusercontent.com/34143366/128872188-39c09727-0867-495d-adf9-921b6e0f87fe.png)

I'am use Anki 2.1.26 in recent KDE Neon user edition.

**Comment by ThoreBor** [comment]
I'm not familiar with KDE Neon, but it looks like this is a KDE Neon specific issue. Does light mode look okay?

**Comment by Nanco300** [comment]
> I'm not familiar with KDE Neon, but it looks like this is a KDE Neon specific issue. Does light mode look okay?

![image](https://user-images.githubusercontent.com/34143366/130323916-e092ec00-8dd5-4656-a1c2-8830bcae0743.png)

**Comment by rodrigolanes** [comment]
On Windows, when in the dark theme, the contrast is also bad.

![image](https://user-images.githubusercontent.com/180106/169409988-a4ea7e21-670b-4ab1-a6ad-ad0b92905a1e.png)
