### ISSUE TITLE
No way to access settings on Mac. Groups do not work on Mac.

### ISSUE THREAD

**Issue by liamreckley** [ThoreBor/Anki_Leaderboard#154]
As the title suggests. There is no way to access settings on Mac. 
The second issue is that there is no way to join groups on Mac as the setting page (which can only be accessed once) does not work.

**Comment by ThoreBor** [comment]
This is a known issue on (some?) macs. You should be able to open the settings by going to Tools>Add-ons>Leaderboards>Config though.

**Comment by liamreckley** [comment]
After messing with it through the config settings it works well. I suppose that is just the way to work with it on Macs that do not work. Thank you.
