### ISSUE TITLE
Account reset?

### ISSUE THREAD

**Issue by avanteGarbage** [ThoreBor/Anki_Leaderboard#155]
**Describe the bug**
Account stats and leaderboard history appear to have been reset? Found myself back in Delta league and my account page showing no history of previous seasons (see scrnshot) 
Also lists me as having no active groups despite the fact that I can open the leaderboard and filter by group (see scrnshot 2)
I've rejoined one of my groups, but haven't rejoined the other

Anyway to rollback my account? Not a huge deal but bit of a bummer to lose 20+ seasons of stats

**Screenshots**
![image](https://user-images.githubusercontent.com/90181004/132182824-682ebe0f-79fc-4cd4-a6e8-d869f9068532.png)
![image](https://user-images.githubusercontent.com/90181004/132182891-dab87783-ff71-48da-9005-9c23c8c13d51.png)

**Steps to reproduce bug**
N/A

**Info**
- Anki version: Version ⁨2.1.44 (b2b3275f)⁩
- Leaderboard version: v.1.7.0

- OS: (e.g. Windows 10)

**Additional context**

I did share my addon21 file with some classmates, and so I'm wondering if this automatically logged them into my account and triggered some database protections when a bunch of different collections started syncing progress from different IPs

**Comment by ThoreBor** [comment]
I restored your stats from the latest backup I had and you're back in Alpha. I'm not sure what exactly went wrong here, but it probably has something to do with you sharing your add-on files (specifically meta.json). It's possible that (one of) your classmates is also logged into your account and overwrote some stuff. Just rejoin the other groups and I think you should be good to go. In the next update, users will have to log in with a password, so this hopefully won't be an issue going forward.
