### ISSUE TITLE
Invalid Token

### ISSUE THREAD

**Issue by Cuhhhhh** [ThoreBor/Anki_Leaderboard#157]
Thank you for the Leaderboard add-on! I've recently been getting an "invalid token" error ever since the most recent update to your addon.

![image](https://user-images.githubusercontent.com/90937614/133858337-15508759-3418-4cd5-aae0-d9f403283eca.png)

The error appears anytime I try to open the leaderboard or sync the leaderboard. I can't sync my data with my account (username is natebg), though I guess this is obvious haha. I do not have autoscroll currently set. I have both the addon and personal setting set to 5 hours past midnight. Please let me know if you need anything else for me, and thank you for your work!

**Info**
- Anki version: 2.1.38
- Leaderboard version: v.1.7.0
- OS: (e.g. Windows 10)

**Comment by ThoreBor** [comment]
Sorry for the inconvenience. Everything should work now. In the next update, you'll have to log in with a password, so this hopefully won't be an issue in the future.
