### ISSUE TITLE
A sleep option

### ISSUE THREAD

**Issue by aboali1hassona** [ThoreBor/Anki_Leaderboard#160]
when I am offline. i face that ADDon -Leaderboard- is trying to connect with the internet
then I must close the message of Alert. 
I propose an option for manual synchronization to this helpful ADDon.
And Also I suggest an option to disable Automatically synchronization during the Anki program opening.

- the Anki synchronization settings have a similar option.

**Comment by ThoreBor** [comment]
You can disable auto-sync in the config.
