### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by aboali1hassona** [ThoreBor/Anki_Leaderboard#162]
what happened?? and how I can fix this ??
`Windows 10 - Anki 2.1.48
`
![Screenshot 2021-10-30 164907](https://user-images.githubusercontent.com/91283119/139539140-9ed89204-7e40-4fa4-9f5d-85cd3a6357d1.png)

**Comment by ThoreBor** [comment]
This is just an old notification. You can just ignore it and it shouldn't appear again.
