### ISSUE TITLE
Next season didn't begin for me

### ISSUE THREAD

**Issue by Jgneves** [ThoreBor/Anki_Leaderboard#164]
**Describe the bug**
Hi! Is it just for me that the new season didn't begin? For me, it shows only some users in the ranking of the league and in the right superior corner it says "The next season is going to start soon"

**Screenshots**
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/73028968/144716353-4397bb08-10ad-4044-9062-3721555cd6a1.png">

**Steps to reproduce bug**

**Info**
- Anki version (2.1.47)
- Leaderboard version (v2.0.0)

- OS: (MAC OS Monterey)

**Comment by ThoreBor** [comment]
I restarted it last Friday. The only reason I can think of why you're seeing is, is that you didn't restart Anki in a while. Could this be the case? The add-on gets the season dates when opening Anki. If that's not the case, do you get any errors when opening Anki?

**Comment by Jgneves** [comment]
Hello, Thore! I'm sorry, I saw the response just today. Thank you very much for the response! I really wasn't restarting Anki! When it was lefting 3 days to the end of the season I restarted it and my league on leaderboard went back to normal. I think that this was really the cause of the problem. Again, thank you for the support and for the great work on the add-on!!! It is awesome :)

**Comment by Jgneves** [comment]
I just tested restarting right now with the new season and don't restart was really the cause of the problem! Now my league started much sooner than it used to start. I usually never restart Anki hahahaha. Thank you again!
