### ISSUE TITLE
I can't get login access.

### ISSUE THREAD

**Issue by huandney** [ThoreBor/Anki_Leaderboard#168]
**Describe the bug**
I can't log into the account, and when I request a password reset, no email is sent to my address.

Username: Huandney
Email: huandney@gmail.com

**Screenshots**
![Capturar](https://user-images.githubusercontent.com/19948348/148489257-bd484fbb-5eea-4ac5-b0e2-469cccdb1a4d.JPG)

**Info**
- Anki version 2.1.40
- Leaderboard 2.0
- Windows 10

**Comment by ThoreBor** [comment]
You didn't add an email address and password to your username yet (this was only added in the last update). Please go to Leaderboard>Config>Account>Add email address and password to old account, and enter an email address and password. If this also doesn't work, please send an email to leaderboard_support@protonmail.com.

**Comment by huandney** [comment]
I sent an email but still haven't received a response.
huandney@gmail.com

**Comment by ThoreBor** [comment]
I sent you a mail just now, sorry for the wait.

**Comment by huandney** [comment]
Thanks!!!
