### ISSUE TITLE
Password reset emails not sending

### ISSUE THREAD

**Issue by ilangleben19** [ThoreBor/Anki_Leaderboard#169]
I've been trying to trigger a password reset because every time I try to log in it says "Something went wrong." I know the username I'm resetting for is correct because, when I try to sign up again, the form tells me the username is already in use. However, even though I put the correct username and every possible email address into the Password Reset form, I never get an email to reset. I've checked Spam as well and nothing there.

What should I do? Thank you very much for your help and for the time you're putting into maintaining this awesome add-on.

**Comment by ThoreBor** [comment]
Please let me know what your username is, and I'll look into it.

**Comment by ilangleben19** [comment]
ilangleben19

Thank you very much for your help.

**Comment by ThoreBor** [comment]
Yep, same issue as #168. Please follow the steps there.

**Comment by ilangleben19** [comment]
Thanks and sorry for duplicate issue.
