### ISSUE TITLE
Gamification suggestion

### ISSUE THREAD

**Issue by cjdduarte** [ThoreBor/Anki_Leaderboard#17]
I would like to suggest (parameterized (on / off), because some may find that it hinders the study) the option that, during the study, if I go up one position (or fall one position) something similar to the screen below appears.

![image](https://user-images.githubusercontent.com/42243532/78284461-da823f80-74f5-11ea-90c0-b717c3755d8b.png)

**Comment by ThoreBor** [comment]
The add-on would have to constantly sync data for this to work. Since this takes a few seconds I'm afraid that this can't be done at the moment.
