### ISSUE TITLE
Delete group and Searching Groups

### ISSUE THREAD

**Issue by Carltin1** [ThoreBor/Anki_Leaderboard#173]
I accidentally opened two groups instead of one. is it possible to delete one of them?

Also: Due to the popularity of the Add-On the Group List gets a little overcrouded. Is it possible to add a Search for group feature?

**Comment by ThoreBor** [comment]
Sure, I can delete it for you. Please send me an email with the email address you signed up with. (leaderboard_support@protonmail.com).

I delete inactive groups regularly, and you can search for groups by typing the name when the drop-down menu is open.
