### ISSUE TITLE
 Bad contrast when in dark theme

### ISSUE THREAD

**Issue by rodrigolanes** [ThoreBor/Anki_Leaderboard#176]
I use Windows 11 with dark theme and the addon presentation looks like the image below:

![image](https://user-images.githubusercontent.com/180106/169410352-492c878b-a769-4c5a-b654-ce968f868184.png)

**Comment by rodrigolanes** [comment]
It's the same subject as ticket #150

**Comment by ThoreBor** [comment]
Thanks for letting me know. Looks like 2.1.50 broke it
