### ISSUE TITLE
Remove myself from Leaderboard/Global and League

### ISSUE THREAD

**Issue by rawrdawg** [ThoreBor/Anki_Leaderboard#183]
**Is your feature request related to a problem? Please describe.**
During review week I will save all my cards so I can go through about 2000 a day to cram for an exam but I do not want to effect the leaderboard and only want my friends to see what I am doing.

**Describe the solution you'd like**
Make it so you can remove yourself from the global leaderboard and a league and only be seen by your friends.

**Additional context**
Another question is if I make a custom study deck to cram a bunch of cards will it show up in reviews?

**Comment by ThoreBor** [comment]
Sorry, I don't think that this is something I'm going to change. The whole point of the global leaderboard is, that it shows everyone. Reviews in a custom deck also count. Sorry for the late response
