### ISSUE TITLE
Bug appears when start ANKI

### ISSUE THREAD

**Issue by DR-3araby** [ThoreBor/Anki_Leaderboard#189]
**Describe the bug**

**Screenshots**

**Steps to reproduce bug**
If possible, step by step instructions for how to reproduce the bug

**Info**
- Anki version (Help>About; e.g. 2.1.24)
- Leaderboard version (Leaderboard>Config>About tab; e.g. v.1.4.4)
- If relevant Add-on config info (start of new day, autoscrolling enabled etc.)
- OS: (e.g. Windows 10)

**Additional context**
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
when tring to start the app this annoying error appeared, but the app works probably
Anki 2.1.54 (b6a7760c) Python 3.9.10 Qt 6.3.1 PyQt 6.3.1
Platform: Linux
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-01-01 18:06:48
Add-ons possibly involved: ⁨41708974⁩

Caught exception:
Traceback (most recent call last):
  File "aqt.progress", line 118, in handler
  File "aqt.main", line 197, in on_window_init
  File "aqt.main", line 290, in setupProfile
  File "aqt.main", line 470, in loadProfile
  File "aqt.hooks_gen", line 3244, in __call__
  File "/home/ahmed/.local/share/Anki2/addons21/41708974/__init__.py", line 52, in profileHook
    gui_hooks.reviewer_will_end.append(self.startBackgroundSync)
NameError: name 'gui_hooks' is not defined

**Comment by ThoreBor** [comment]
Thanks for reporting this. It will be fixed in the next update. In the meantime you can disable the "Sync when deck is finished" in the settings, then you won't get this error message.
