### ISSUE TITLE
it says error after the recent update :(

### ISSUE THREAD

**Issue by lllcvy** [ThoreBor/Anki_Leaderboard#191]
**Describe the bug**

**Screenshots**

**Steps to reproduce bug**
If possible, step by step instructions for how to reproduce the bug

**Info**
- Anki version (Help>About; e.g. 2.1.24)
- Leaderboard version (Leaderboard>Config>About tab; e.g. v.1.4.4)
- If relevant Add-on config info (start of new day, autoscrolling enabled etc.)
- OS: (e.g. Windows 10)

**Additional context**

**Comment by ThoreBor** [comment]
Please see #189 for this
