### ISSUE TITLE
Anki Leaderboard Failing to work

### ISSUE THREAD

**Issue by shawn-moyo** [ThoreBor/Anki_Leaderboard#192]
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-01-02 10:40:43

Caught exception:
Traceback (most recent call last):
  File "aqt.main", line 350, in onOpenProfile
  File "aqt.main", line 470, in loadProfile
  File "aqt.hooks_gen", line 3244, in __call__
  File "C:\Users\shawn\AppData\Roaming\Anki2\addons21\41708974\__init__.py", line 52, in profileHook
    gui_hooks.reviewer_will_end.append(self.startBackgroundSync)
NameError: name 'gui_hooks' is not defined

**Comment by ThoreBor** [comment]
See #189
