### ISSUE TITLE
Home leaderboard doesn't display

### ISSUE THREAD

**Issue by Redixit** [ThoreBor/Anki_Leaderboard#198]
The home leaderboard isn't displaying for some reason. It may be due to add-on incompatibilities, but I am unaware of which add-on may have caused this problem. I will provide a screenshot with my add-ons in case it can help.

![Screenshot 2023-01-23 at 7 07 08 PM](https://user-images.githubusercontent.com/123389398/214074069-893cf931-5754-403f-bfd3-79c4eae58535.jpg)

![Screenshot 2023-01-23 at 7 06 40 PM](https://user-images.githubusercontent.com/123389398/214074101-95a0fbe1-deb3-43e9-88e6-aa8f9f5ff2a9.jpg)

Anki version 2.1.54
Leaderboard v3.0.2
macOS Ventura 13.1
MacBook Pro M1 Chip

**Comment by ThoreBor** [comment]
What is your default Leaderboard? Please check if it works when you set the default Leaderboard to `Global` (Leaderboard>Config>Setting>Defaut Leaderboard). Also make sure to sync the home screen leaderboard after the changes (Shift + S, or Leaderboard>Sync and update home screen leaderboard).

**Comment by Redixit** [comment]
> What is your default Leaderboard? Please check if it works when you set the default Leaderboard to `Global` (Leaderboard>Config>Setting>Defaut Leaderboard). Also make sure to sync the home screen leaderboard after the changes (Shift + S, or Leaderboard>Sync and update home screen leaderboard).

It works now. Thanks!
