### ISSUE TITLE
add on not working after Anki update today 

### ISSUE THREAD

**Issue by ak-hash** [ThoreBor/Anki_Leaderboard#205]
updated to anki version intel. 2.1.60 qt 6 today and this pops up 

<img width="1280" alt="Screen Shot 2023-03-05 at 2 08 07 PM" src="https://user-images.githubusercontent.com/56414365/222988745-8d6e2ae1-38db-497f-b90d-628b629b2c9a.png">

**Comment by ThoreBor** [comment]
You'll get this error messages sometimes, when the server is too busy and times out (or if you're not connected to the internet). Nothing to worry about and not related to the update.
