### ISSUE TITLE
Unable to access Anki Preferences

### ISSUE THREAD

**Issue by lorfrian** [ThoreBor/Anki_Leaderboard#214]
After installing Leaderboard it's not possible to access the general Anki settings anymore. Every time I click on Anki -> Preferences the preferences of Leaderboard will open. The issue is resolved when Leaderboard addon is deactivated.

Leaderboard v3.0.2

    Anki 2.1.62 (77dd1dc1) Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
    Platform: macOS-13.1-arm64-arm-64bit
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2023-05-17 09:33:55

**Comment by ThoreBor** [comment]
Please see #195
