### ISSUE TITLE
It logs you out when you login on a different device

### ISSUE THREAD

**Issue by Xemorr** [ThoreBor/Anki_Leaderboard#215]
**Describe the bug**
It logs you out when you login on a different device

**Steps to reproduce bug**
Login on one device, (may need to turn off first device?), login on other device, try to open leaderboard on first device

**Info**
- Anki version 2.1.56
- Leaderboard version 3.0.2
- If relevant Add-on config info (start of new day, autoscrolling enabled etc.)
- OS: (e.g. Windows 10)

**Additional context**
It drives me insane

**Comment by ThoreBor** [comment]
Please see #197
