### ISSUE TITLE
The new season for the league hasn't started yet

### ISSUE THREAD

**Issue by valogonor** [ThoreBor/Anki_Leaderboard#217]
**Describe the bug**
Typically, a new two-week season starts within a few days of the last season ending, but it's been about a week since the end of the last season, and the next one has yet to start.

**Screenshots**
![image](https://github.com/ThoreBor/Anki_Leaderboard/assets/43195349/10b2ee74-7034-49f3-bd51-d9bb37def4cb)

**Steps to reproduce bug**
If possible, step by step instructions for how to reproduce the bug

**Info**
- Anki version (Help>About; e.g. 2.1.24) Version ⁨2.1.56 (07fd88dd)
- Leaderboard version (Leaderboard>Config>About tab; e.g. v.1.4.4) Leaderboard v3.0.2
- If relevant Add-on config info (start of new day, autoscrolling enabled etc.)
- OS: (e.g. Windows 10)

**Additional context**

**Comment by ThoreBor** [comment]
Thanks for letting me know
