### ISSUE TITLE
v1.3: Bug in Streak

### ISSUE THREAD

**Issue by cjdduarte** [ThoreBor/Anki_Leaderboard#22]
In this new version, my streak dropped.
It dropped from 164 to 68.

![image](https://user-images.githubusercontent.com/42243532/78372790-170a7580-75a0-11ea-81ab-6a028a9a6f0a.png)

**Comment by ThoreBor** [comment]
Did you set the time when your day starts in the config?

**Comment by cjdduarte** [comment]
I haven't changed any settings. I just updated the addon and reopened Anki.

![image](https://user-images.githubusercontent.com/42243532/78373135-8e400980-75a0-11ea-83ef-add80c1a3c34.png)

**Comment by cjdduarte** [comment]
In version 1.2 it was OK.

**Comment by ThoreBor** [comment]
Try setting it to something like 4. And i need to fix that typo

**Comment by ThoreBor** [comment]
in v1.2 the day started at 4 am

**Comment by cjdduarte** [comment]
It worked.
Suggestion. The addon should be reading this field:

![image](https://user-images.githubusercontent.com/42243532/78373785-6a30f800-75a1-11ea-9002-25a17cba7082.png)

**Comment by ThoreBor** [comment]
Okay, great. Yes, that's the plan, but i didn't figure out how to read the value from this field yet.

**Comment by ThoreBor** [comment]
I uploaded a hotfix that sets the default to 4am like in v1.2 for now and fixed the typo.
