### ISSUE TITLE
anki > Preferences goes to Leaderboard Preferences instead of anki preferences

### ISSUE THREAD

**Issue by pandaprincess333** [ThoreBor/Anki_Leaderboard#220]
**Describe the bug**
When Leaderboard is toggled on, Anki > Preferences makes the Leaderboard config page pop up instead of the the Anki preferences

When Leaderboard is disabled, the correct window pops up.

Any idea how to fix this?

**Comment by nxzoo** [comment]
I also have this issue on version: 
Version ⁨2.1.65 (aa9a734f)⁩
Python 3.9.15 Qt 6.5.0 PyQt 6.5.0
