### ISSUE TITLE
Feature request: Sort by Country

### ISSUE THREAD

**Issue by succil** [ThoreBor/Anki_Leaderboard#24]
It would be awesome if:
1. We could put a flag of our country aside the nickname;
2. We could see our rank in our own country.

Thank you!

**Comment by ThoreBor** [comment]
That's a good idea. I'll work on it!

**Comment by DoctorToBeIn23** [comment]
I know there has been the request of different communities like learning languages and Step 1, how is that looking?

**Comment by ThoreBor** [comment]
@DoctorToBeIn23  So you would like to for example only see people that study languages? @succil  I'll try to include sort by country in the next update. The flags are probably going to take longer.

**Comment by DoctorToBeIn23** [comment]
Yeah like if you can create a few main leaderboards and you can subscribe to any you want. So Step 1 (one most med students use Anki for) Language learning...

**Comment by ThoreBor** [comment]
Okay, I created a new feature request for this (#31).  This probably won't be included in the next update, but'll work on it.

**Comment by DoctorToBeIn23** [comment]
Thank you very much for your responsiveness!!!
