### ISSUE TITLE
Streak not synced with heatmap and cards studied don't match up

### ISSUE THREAD

**Issue by MagnetoMag169** [ThoreBor/Anki_Leaderboard#25]
Greetings,

The streak on leaderboard does not sync with my heatmap and the cards that I have studied also don't match up. I have already updated to the newest version of the add on and anki. Can you look into this? Thanks!
![image](https://user-images.githubusercontent.com/63136224/78417968-531ff380-75fd-11ea-8b74-655319258af2.png)
![image](https://user-images.githubusercontent.com/63136224/78417973-6763f080-75fd-11ea-9453-413edf542ebf.png)

**Comment by ThoreBor** [comment]
Just to make sure, please go to Leaderboard>About and tell me exactly what version your using. What are your settings in Leaderboard>Config for the start of the new day?

**Comment by MagnetoMag169** [comment]
Thanks for your reply! I am using v 1.3.1 as shown below:
![image](https://user-images.githubusercontent.com/63136224/78440743-79658380-763d-11ea-9ab3-b64f50fc8630.png)

My config is 4 hours past midnight (which also matches my preferences).
![image](https://user-images.githubusercontent.com/63136224/78441004-8da98080-763d-11ea-97a5-4c97b3737656.png)
![image](https://user-images.githubusercontent.com/63136224/78441171-98fcac00-763d-11ea-8598-621d51f35f17.png)

Thanks.

**Comment by ThoreBor** [comment]
That's weird. If you use Ankidroid please check if it's a similar problem to #27 . If not, you can export your Anki collection and send it to me if you want. Then I could take a closer look.

**Comment by MagnetoMag169** [comment]
I'm don't use ankidroid - I'm only using it on my computer. I'm testing it out so far and it seems to be pretty similiar this morning (I'm in CST timezone). My only concern is that it freezes my number at around 7:00pm CST every day. So if I did more cards after that time, it would not add onto my total number.

What I'm seeing so far:
![image](https://user-images.githubusercontent.com/63136224/78450195-76b95d00-7642-11ea-8aed-2a0471cb9b3f.png)

**Comment by MagnetoMag169** [comment]
Update: Starting to become more different between the two numbers:
![image](https://user-images.githubusercontent.com/63136224/78451047-a0758280-7648-11ea-991e-ec94bd40cc3d.png)

**Comment by ThoreBor** [comment]
Thanks for the update. Please go to Tools>Add-On>Select Leaderboard>View Files. There should be a file called "meta.json".  What's inside?

**Comment by MagnetoMag169** [comment]
There is the file "meta.json". However, I cannot open the file without the necessary opener.
![image](https://user-images.githubusercontent.com/63136224/78454027-1256c780-765b-11ea-97a9-28ba20fee4d5.png)

**Comment by ThoreBor** [comment]
You can just right click on it and open it with the editor

**Comment by MagnetoMag169** [comment]
This is what I see when I open it in notepad:
{"name": "Leaderboard", "mod": 1585953537, "min_point_version": 0, "max_point_version": 22, "branch_index": 0, "config": {"new_user": "False", "username": "MagnetoMed", "friends": ["MagnetoMed", "anbu5000", "WutsDatBud", "DocBrk", "AusernameC", "drcabbage", "MV69"], "newday": "4"}}

**Comment by ThoreBor** [comment]
Okay, thanks. This is exactly how it should be. I don't know what the problem is. You could try to just create a new account and see if this changes anything, but I doubt it. I'll think about it. What might help to figure this out is if you send me all your settings in ankis preferences.

**Comment by MagnetoMag169** [comment]
Sure no problem, thanks for looking into this. Here are all my preferences:
![image](https://user-images.githubusercontent.com/63136224/78454670-27355a00-765f-11ea-87f5-1c845a2cbf5d.png)
![image](https://user-images.githubusercontent.com/63136224/78454703-55b33500-765f-11ea-9387-e0217d2cb686.png)
![image](https://user-images.githubusercontent.com/63136224/78454688-361c0c80-765f-11ea-88a1-7879b213e4bb.png)
![image](https://user-images.githubusercontent.com/63136224/78454691-3c11ed80-765f-11ea-9468-214c1fea3e54.png)

Let me know if you need anything else

**Comment by ThoreBor** [comment]
Thanks, what's "Muffins"? Is this another add-on? Maybe also let me know what add-ons you're using.

**Comment by MagnetoMag169** [comment]
Muffins is the hoochie series add on (for random appearance of review cards). 

Here are my addons
![image](https://user-images.githubusercontent.com/63136224/78454844-349f1400-7660-11ea-9348-64dc729e5cf5.png)
![image](https://user-images.githubusercontent.com/63136224/78454851-3a94f500-7660-11ea-9e23-fbdafe7c0788.png)

**Comment by ThoreBor** [comment]
Alright, thanks. Maybe the leaderboard is not compatible with one of those other add-ons. I'll check it out.

**Comment by MagnetoMag169** [comment]
Sounds great. Thanks for checking - I appreciate your help!

**Comment by MagnetoMag169** [comment]
Update: All my stats on leaderboard freezes at 7 pm CST every day (which is 5 hours behind UTC if that matters). So if I did more cards after that time, it would not add onto my total number.

**Comment by ThoreBor** [comment]
Try to disable all add-ons but the leaderboard (Tools>Add-On>Select>Toggle Enabled) and restart Anki.

**Comment by MagnetoMag169** [comment]
There are some add on's that I would rather not disable or else it may ruin my card scheduling. Can I try to disable only some of them?

**Comment by ThoreBor** [comment]
Okay, I think I might've found the mistake anyway. Some of the epoch milliseconds were converted to gmt instead of local time. I can probably release the new version tomorrow, then you can check if this fixed your problem.

**Comment by MagnetoMag169** [comment]
Sounds great - thanks for letting me know.
