### ISSUE TITLE
Leaderboard doesn't count reviews done on mobile.

### ISSUE THREAD

**Issue by RGR258** [ThoreBor/Anki_Leaderboard#27]
Whilst i mostly use the desktop version of anki, I use ankidroid when I'm away from my computer, and I've noticed that the leaderboard doesn't count reviews done on ankidroid.
To be honest, this doesn't bother me too much, but it would be cool if it did count those as well.

**Comment by ThoreBor** [comment]
I use ankidroid >90% and it works for me. Does this affect all the stats or just reviews? Also did you sync Anki/Ankidroid before opening the leaderboard?

**Comment by RGR258** [comment]
Oh I see. Maybe It's just me.
Yes i synced beforehand. I always sync before swapping between the 2.
I'd noticed for a few days that the leaderboard count didn't match my total cards for the day.
I realised today that the difference matched the few cards I did on ankidroid in the morning before turning on my computer.

**Comment by ThoreBor** [comment]
Please go to Leaderboard>About and check what version you are using.

**Comment by RGR258** [comment]
I'm using version 1.3.1.

**Comment by ThoreBor** [comment]
That's odd. So only the cards stats are off, but the streak and time are accurate? When does your new day start (Leaderboard>Config)?

**Comment by RGR258** [comment]
Ahhh, you've solved it!
My new day starts at midnight, however it was 11 hours after midnight on ankidroid (i had recently been in a different timezone which must have messed with it).
Hadn't affected my reviews though, so i hadn't noticed.
The leaderboard is now counting reviews done on ankidroid.
Thanks for your help!

**Comment by ThoreBor** [comment]
Great!
