### ISSUE TITLE
Friends Continue to Be Removed from my LeaderBoard List

### ISSUE THREAD

**Issue by MtnManBearPig** [ThoreBor/Anki_Leaderboard#29]
I noticed yesterday (04/04) that a few of my friends did not show up on my leaderboard list. After texting them they said that they were having issues as well with some of their friends being lost. We both attempted to re-add each other and still are not able to see one another. 

Today, all of the people on my friends list disappeared (including my own username).

**Info**
- Anki version (2.1.22)
- Leaderboard version (v.1.3)
- Start of new day (4)
- OS: (Windows)

**Comment by ThoreBor** [comment]
Do you see your friends in the global tab? Because the leaderboard only shows people that synced (e.g. opened) the leaderboard the same day as you.

**Comment by MtnManBearPig** [comment]
I looked through most of the names and found 1. Is there a search feature that I can use instead of looking through all 200+ names?

**Comment by ThoreBor** [comment]
Unfortunately not yet. But you can check the raw data here: https://ankileaderboard.pythonanywhere.com/getstreaks/ Ctrl+F to search there name and check their last sync date. Or tell me their names then I do it.

**Comment by MtnManBearPig** [comment]
Most of them synced yesterday, but I was not able to seem them either yesterday or today. Does the add-on remove the users from my friend list if they do not sync that same day?

**Comment by ThoreBor** [comment]
No, they shouldn't be removed from your friend list. You can check this if  you go to Tools>Add-On>Leaderboard> Config. 
You only see them if they synced their stats since your day began (default 4am). To check if this is the issue, you could ask one of your friends that you don't see to sync their data and check afterwards if you see them on the leaderboard.

**Comment by ThoreBor** [comment]
Please check if v1.4.1 fixed your problem.
