### ISSUE TITLE
Monthly leaderboard

### ISSUE THREAD

**Issue by sopoforic** [ThoreBor/Anki_Leaderboard#30]
It would be nice to have, in addition to the daily leaderboard, a similar set on a moving 30-day window.

Right now, the only time the leaderboards will show interesting data for you personally will be when you have finished everything for the day--any earlier, and you're just at the bottom of the list since you haven't done all your reviews, and then in the morning everything is gone again. So, it's not much motivation.

If there were leaderboards on a moving window, then you could use that to motivate yourself to keep your rank up from day to day, and it'd reward consistency.

**Comment by ThoreBor** [comment]
Thanks for the suggestion. Do you mean a monthly leaderboard like how many reviews you did since the 1st or in the last 30 days?

**Comment by sopoforic** [comment]
Above, I suggested a moving 30-day window. I think that would reward consistency more than a leaderboard that resets at the top of the month.

**Comment by ThoreBor** [comment]
Okay, I wasn't sure if I understood it correctly. I'll try to include it in the next update

**Comment by sopoforic** [comment]
Fantastic! Thank you!
