### ISSUE TITLE
Country - free-text doesn't work. Perhaps choose from a list?

### ISSUE THREAD

**Issue by bradydjohnson** [ThoreBor/Anki_Leaderboard#35]
**Describe the bug**
I updated the add-on this afternoon (4/7/2020). When indicating my country (USA), it's unclear whether I should type USA, United States of America, United States, etc. 

**Expected behavior**
Select from a list seems standard on the internet.

**Screenshots**
<img width="597" alt="image" src="https://user-images.githubusercontent.com/6741590/78716790-2dd50300-78e5-11ea-8256-bcc51bd2a019.png">

**Info**
- Anki version 2.1.23
- Leaderboard version - unclear, can't find Leaderboard > About
- Start of new day 4
- OS: Mac

**Comment by ThoreBor** [comment]
Yes, I was afraid that this might be a problem. I'll try to make a dropdown list.

**Comment by ThoreBor** [comment]
Fixed it now in v1.4.1
