### ISSUE TITLE
Suggestion in v1.4

### ISSUE THREAD

**Issue by cjdduarte** [ThoreBor/Anki_Leaderboard#36]
CONGRATULATIONS for the update. But let's go !!!!

**1. Decrease line spacing**

![image](https://user-images.githubusercontent.com/42243532/78716547-709ed700-78f5-11ea-95e2-5fb8c3d41f94.png)

**2. insert punctuation in the thousands count**

**`ex: 6.880 and 3.311`**

![image](https://user-images.githubusercontent.com/42243532/78716670-b2c81880-78f5-11ea-9d96-89140f031a00.png)

**3. By clicking on sort the column, by default it shows from smallest to largest. If possible, bring initially from the largest to the largest, as this is what we seek. Possibly everyone will click twice in the column.**

![image](https://user-images.githubusercontent.com/42243532/78716899-1a7e6380-78f6-11ea-9d32-8e54d86c1ed1.png)

**4. If possible, bring the list of countries. Many users will end up typing in their language or they will not know their country's name in English or will misspell (this will happen):** [Another Issues](https://github.com/ThoreBor/Anki_Leaderboard/issues/35):

![image](https://user-images.githubusercontent.com/42243532/78717099-73e69280-78f6-11ea-8f1a-f5b6cd3bb37c.png)

**5. Insert study type title.**

![image](https://user-images.githubusercontent.com/42243532/78717216-ac866c00-78f6-11ea-879b-fde5aa32099a.png)

**6. If possible, in the GLOBAL, FRIEND and COUNTRY tab, bring the column for the type of study.**

![image](https://user-images.githubusercontent.com/42243532/78717216-ac866c00-78f6-11ea-879b-fde5aa32099a.png)

![image](https://user-images.githubusercontent.com/42243532/78717138-86f96280-78f6-11ea-8b86-a3c78fb50683.png)

**7. The colors of the TOP 3 and friends of each tab are gone.**

![image](https://user-images.githubusercontent.com/42243532/78717706-6a115f00-78f7-11ea-8ec8-e055d2bf43ab.png)

**8. Back with color in our name tag**

![image](https://user-images.githubusercontent.com/42243532/78717825-988f3a00-78f7-11ea-8665-48f4233692f3.png)

**Info**
- Anki version (2.1.22)
- Leaderboard version (v.1.4)
- Start of new day (4)
- OS: (Windows)

**Comment by ThoreBor** [comment]
1. It's at the minimum width. I can't make it smaller, because the of the title of that column. Also can you send me a screenshot of the whole window. Looks like it's larger than on my side.
2. Will do
3. That also annoys me, but I haven't figured out how to change the order from descending to ascending. 
4. Yes, I'll try to do that.
5. Not sure if this would work. Some might type "Language" other e.g. "German" etc.
6. That's possible. I did it when i worked on this version, but decided not to include it, because i felt like the window was to big and there was too much information.
7. I'm aware of that. The problem here is not coloring the first three places, but deleting the color when you sort the leaderbord. 
8.  So your username is not green and friends aren't blue? They should be.

**Comment by cjdduarte** [comment]
1. _It's at the minimum width. I can't make it smaller, because the of the title of that column. Also can you send me a screenshot of the whole window. Looks like it's larger than on my side._
**sorry, i was referring to the height of the line. Not the width.**

2. OK
3. OK
4. OK
5. OK

6. _That's possible. I did it when i worked on this version, but decided not to include it, because i felt like the window was to big and there was too much information._
**It would be interesting, because normally those who study languages, the amount studied per day is usually much higher, due to the simplicity of the cards. Then I can compare it with someone who studies something similar.**

7. OK

8. _So your username is not green and friends aren't blue? They should be._
**He paints only on the global tab. In the others, my name is not marked. In the previous version, it was marked.**

**Comment by ThoreBor** [comment]
Alright, thanks for your suggestions.

**Comment by cjdduarte** [comment]
About item 1: I still prefer the font style (type, size, line spacing) of version 1.3.
In version 1.4 it became more difficult to read in the new style.

![image](https://user-images.githubusercontent.com/42243532/78842214-cd71be80-79d5-11ea-932b-a055897faca1.png)

![image](https://user-images.githubusercontent.com/42243532/78842222-d2367280-79d5-11ea-8804-a18f6eb17637.png)
