### ISSUE TITLE
Reviews past 30 days

### ISSUE THREAD

**Issue by cjdduarte** [ThoreBor/Anki_Leaderboard#37]
Where does this number come from in the statistics?

I was unable to validate this information on Anki. I didn't find her in any report. What formula are you using?

**Screenshots**
![image](https://user-images.githubusercontent.com/42243532/78719356-2ff58c80-78fa-11ea-82e9-bd6421420403.png)

**Info**
- Anki version (2.1.22)
- Leaderboard version (v.1.4)
- Start of new day (4)
- OS: (Windows)

**Comment by ThoreBor** [comment]
There's a table called revlog in ankis database. It contains every review you've ever did. They're timestamped and the add-on just counts the reviews between today and 30 days ago. 
The database structure is explained [here](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure).

**Comment by cjdduarte** [comment]
I know.

My question is related to the fact that this value does not exist in any report. I understand that he should hit this one:

![image](https://user-images.githubusercontent.com/42243532/78778229-54408000-7971-11ea-9f42-4bd1e2b895d2.png)

![image](https://user-images.githubusercontent.com/42243532/78778290-6f12f480-7971-11ea-8d97-a4217bb24a30.png)

**Comment by cjdduarte** [comment]
I realized that he doesn't show the cards studied on the day. Only the next day.
I just studied some cards and that number hasn't changed.

In comparison to the previous image, the value comes out of 6,999 and went to 7,016; However in the addon it continues with 7,001.

![image](https://user-images.githubusercontent.com/42243532/78780516-22c9b380-7975-11ea-94a5-825707f792a5.png)

![image](https://user-images.githubusercontent.com/42243532/78780565-32e19300-7975-11ea-9acb-7e6f249be51f.png)

**Comment by cjdduarte** [comment]
Yesterday it was 6,999.
Today I studied 17.
Total 7,016.

addon: yesterday and today informs 7.001.

**Comment by ThoreBor** [comment]
Thanks for letting me know. I'll look into it.

**Comment by ThoreBor** [comment]
Fixed in next version
