### ISSUE TITLE
Multiple Computers

### ISSUE THREAD

**Issue by drmarmalademd** [ThoreBor/Anki_Leaderboard#4]
Is it possible for our logins to sync across multiple computers? I use Anki on desktop and my laptop; but the account I made on my desktop is not working on my laptop (says account doesn't exist when I try to log in).

Quick edit: if I try to create an account on my laptop with the same username, it says username already exists. But if I try to log in, it says account doesn't exist. My laptop is Windows, Anki 2.1.22 and my desktop is mac, Anki 2.1.23.

**Comment by ThoreBor** [comment]
Don't know what could cause that at the moment. I tried it and it worked for me. Keep in mind that the username is case sensitive.

**Comment by drmarmalademd** [comment]
Hm. Still not working for me. I've made sure the case is correct for both username and password. I'll keep messing around with it to see if I can find the root of the problem as well.

**Comment by ThoreBor** [comment]
To login you only have to enter your username in the field at the bottom.

**Comment by drmarmalademd** [comment]
Ah, gotcha. That appears to work. I'll close out the issue.

Side note - that isn't too clear. I would recommend making a ReadMe page for your add-on with clarifications such as that or changing the wording on the log-in page - I assumed username should go in the first field.

Cheers!

**Comment by ThoreBor** [comment]
Alright. You're right, that's a little unclear. Might add a password later, but for now I thought that this was the easiest solution.
