### ISSUE TITLE
"About" window

### ISSUE THREAD

**Issue by cjdduarte** [ThoreBor/Anki_Leaderboard#49]
![image](https://user-images.githubusercontent.com/42243532/79045095-a1298e00-7bdf-11ea-86c4-b5dfb0637d64.png)

When I click on the github link in the "About" window, the texts disappear.

![image](https://user-images.githubusercontent.com/42243532/79045107-b43c5e00-7bdf-11ea-9a6d-7d79731d8fec.png)

**Info**
- Anki version (Help>About; e.g. 2.1.22)
- Leaderboard version (Leaderboard>About; e.g. v.1.3)
- Start of new day (Leaderboard>Config; e.g. 4)
- OS: (e.g. Windows)

**Additional context**

**Comment by ThoreBor** [comment]
That's weird, thanks for letting me know.

**Comment by ThoreBor** [comment]
Found the issue. I set `openExternalLinks` to `True`.
