### ISSUE TITLE
Streak not synced with heatmap

### ISSUE THREAD

**Issue by kk1995** [ThoreBor/Anki_Leaderboard#5]
For example, my streak on the leaderboard is 17 days, although I have 73 days streak according to heatmap add on.

**Comment by ThoreBor** [comment]
I'm aware of the problem and I'll try to fix it soon. The problem is most likely that the new day starts at midnight. Is it possible that you only reviewed cards after 0:00 am 18 days ago?

**Comment by kk1995** [comment]
That's very possible. I did not study many cards 18 days ago. I'm not sure if there is a way to check that though.

**Comment by Willz7** [comment]
> That's very possible. I did not study many cards 18 days ago. I'm not sure if there is a way to check that though.

[Alt Text](url)
You can hover heatmaps 18 days ago like this [Heatmap addon](https://i.imgur.com/APWCfMD.png)

**Comment by kk1995** [comment]
> 
> 
> > That's very possible. I did not study many cards 18 days ago. I'm not sure if there is a way to check that though.
> 
> You can hover heatmaps 18 days ago like this ![Heatmap addon](https://camo.githubusercontent.com/076c1edb034e7d4840f909dba7342e928159490e/68747470733a2f2f692e696d6775722e636f6d2f41505743664d442e706e67)

yep but I'm not sure I can find exactly when I did those reviews. The hour when I did them.

**Comment by JasjoL** [comment]
If you click the day you'll see cards that you haven't reviewed again since that day. Click one of the cards then click "Cards" on toolbar at top then "info"

**Comment by DoctorToBeIn23** [comment]
Similar issue I have a 300+ day streak but leaderboard says 1 day

**Comment by kk1995** [comment]
> 
> 
> If you click the day you'll see cards that you haven't reviewed again since that day. Click one of the cards then click "Cards" on toolbar at top then "info"

So I did what you said and here's the log for one of the cards I reviewed 18 days ago (on 3/15):
![image](https://user-images.githubusercontent.com/11636148/78184897-3d150600-7438-11ea-8b15-c03d5a2437b4.png)

To my surprise, I did not review these cards after midnight. So the problem with new day starting after midnight does not seem to apply here.

**Comment by ThoreBor** [comment]
Okay, thank you for the info.

**Comment by ThoreBor** [comment]
It would be great if someone with this issue could send me their complete database, so i can find out what the problem is.

**Comment by DoctorToBeIn23** [comment]
https://drive.google.com/open?id=1TLkIaJ2y32QBUuETgvAwtzcr-VBf74KC

**Comment by Lol4Funzies** [comment]
Is it possible that the leaderboard is pulling data off of a universal 00:00 rather than it being based on one's relative timezone? I pulled up the leaderboard now at 21:55 US Eastern Time and the leaderboard has changed dramatically from when I was on it a few hours ago. My own stats are also gone from the leaderboards as if I haven't done any Anki today. I'm no programmer by any means but I figured I would share those thoughts and observations!

**Comment by jdnguyenswin** [comment]
Mine is an extreme case: leaderboard streak says "0", heatmap streak say 307. Did I do something wrong in setting up the account incorrectly?

**Comment by ThoreBor** [comment]
@Lol4Funzies  That's probably another issue. Yes, for a couple hours the Review and Leaderboard only showed people that synced their data after 0:00 UTC. I changed it now to how it was before, but in the next update you'll only see people that synced their stats on the same day as you.

**Comment by ThoreBor** [comment]
@DoctorToBeIn23  I looked at your data. The problem here is definitely that reviews after midnight aren't counted. Apparently you only did reviews after midnight two days ago so that's why the leaderboard streak is only 2 days.

**Comment by ThoreBor** [comment]
I just updated the add-on. Please check if this fixed the issue for you @kk1995  @DoctorToBeIn23 @jdnguyenswin

**Comment by kk1995** [comment]
My streak number is in sync now. Thank you for looking into this!

**Comment by jdnguyenswin** [comment]
@ThoreBor Thank you. Mine still says 0 days on the streak.
