### ISSUE TITLE
Add-ons page configuration option does not open.

### ISSUE THREAD

**Issue by cjdduarte** [ThoreBor/Anki_Leaderboard#50]
![sample](https://user-images.githubusercontent.com/42243532/79045280-ae934800-7be0-11ea-846f-2984dd530800.gif)

**Comment by ThoreBor** [comment]
Thanks for letting me know. You can also open the config by going to Leaderboard(in the toolbar)>Config. Does this work for you?

**Comment by cjdduarte** [comment]
> Thanks for letting me know. You can also open the config by going to Leaderboard(in the toolbar)>Config. Does this work for you?

Yes. From the menu "Leaderboard" works. Only by that way who does not work.

**Comment by ThoreBor** [comment]
Alright, I'll look into it

**Comment by ThoreBor** [comment]
Solved it. Will be fixed in next update.
