### ISSUE TITLE
Suggestion in the tab "friends"

### ISSUE THREAD

**Issue by cjdduarte** [ThoreBor/Anki_Leaderboard#51]
1. Shows names sorted alphabetically. Facilitates localization
2. Create the option to import, export and "delete all" friends. In the option to import, validate and do not duplicate the name if it already exists. We have a group on the telegram where everyone uses Anki and we have to keep sending the list several times to ensure that everyone has a "complete" list of friends. With this option of importing, it would be much easier.

![image](https://user-images.githubusercontent.com/42243532/79045514-ecdd3700-7be1-11ea-81a8-d97d61dfe781.png)

**Comment by ThoreBor** [comment]
Just import them from a text file, or what did you had in mind?

**Comment by cjdduarte** [comment]
Simple text file with friends list.

**Comment by ThoreBor** [comment]
Included it in the update.
