### ISSUE TITLE
Color error during sorting.

### ISSUE THREAD

**Issue by cjdduarte** [ThoreBor/Anki_Leaderboard#52]
![sample2](https://user-images.githubusercontent.com/42243532/79046206-dd5fed00-7be5-11ea-8b19-0b124a39567d.gif)

**Info**
- Anki version (Help>About; e.g. 2.1.22)
- Leaderboard version (Leaderboard>About; e.g. v.1.3)
- Start of new day (Leaderboard>Config; e.g. 4)
- OS: (e.g. Windows)

**Additional context**

**Comment by cjdduarte** [comment]
I think the error is only in the "Friends" tab.
In the tab of the country and Law (my case), that's correct. the names in white are not in my list of friends.

**Comment by ThoreBor** [comment]
Found the bug. I'll probably upload a new version tonight, after a fixed a few other issues.
