### ISSUE TITLE
Error canceling importing in the "friends" tab.

### ISSUE THREAD

**Issue by cjdduarte** [ThoreBor/Anki_Leaderboard#54]
![image](https://user-images.githubusercontent.com/42243532/79055668-4024a900-7c25-11ea-90b8-6d37a7651da2.png)

![image](https://user-images.githubusercontent.com/42243532/79055612-d2787d00-7c24-11ea-8c35-7a7f8bd7cc97.png)

**Comment by cjdduarte** [comment]
Can you implement the option to export the list?

**Comment by ThoreBor** [comment]
The bug will be fixed in the next version and you'll be able to export the friends list to text file in the add-on folder.
