### ISSUE TITLE
Leaderboard Coming Up Blank - United States & Medical School Anki

### ISSUE THREAD

**Issue by BananaQuee** [ThoreBor/Anki_Leaderboard#56]
Other lists seem to be working fine, like 'Global', 'Law', & 'Languages', but 'United States' and 'Medical School Anki' are coming up completely blank.

**Comment by khonkhortisan** [comment]
My brother and I both set United States and it was still blank.

**Comment by rumDMC** [comment]
I've had the same issue for a few days now. Any way to fix it on my end?

**Comment by ThoreBor** [comment]
I just released a patch that should fix the problem.
