### ISSUE TITLE
Blank Leaderboard when autoscroll is enabled

### ISSUE THREAD

**Issue by shawnkim332** [ThoreBor/Anki_Leaderboard#57]
**Describe the bug**
when I click "Automatically Scroll to Yourself" box, the leaderboard goes blank.

**Expected behavior**
I hope the leaderboard screen doesn't go blank.

**Screenshots**
<img width="1600" alt="Screen Shot 2020-04-15 at 2 27 21 PM" src="https://user-images.githubusercontent.com/63745149/79374330-42d51600-7f25-11ea-9dab-09a742731507.png">
<img width="1600" alt="Screen Shot 2020-04-15 at 2 27 55 PM" src="https://user-images.githubusercontent.com/63745149/79374434-52ecf580-7f25-11ea-93ce-ea5b3072f59c.png">
<img width="1600" alt="Screen Shot 2020-04-15 at 2 28 41 PM" src="https://user-images.githubusercontent.com/63745149/79374602-6e580080-7f25-11ea-8654-e81b6a6b8354.png">

**Info**
- Anki version 2.1.23
- Leaderboard version 1.4.3.1
- Start of new day (4
- OS: Mac

**Additional context**

**Comment by ThoreBor** [comment]
Thank you for letting me know. And you don't get any error messages? I can only officially support Anki 2.1.22 for now. So the Anki version or using mac could be the problem. It would be interesting to know whether or not other 2.1.23 users have the same problem.

**Comment by ThoreBor** [comment]
#60 and #61 are having the same problem and are also using Anki 2.1.23. If anybody else has the same issue, please report it here.

**Comment by ThoreBor** [comment]
Small update: I just updated to Anki 2.1.24 (for windows) and I've not been able to reproduce this bug.
