### ISSUE TITLE
My friends only pop into the leaderboard if they have loaded the add-on that same day

### ISSUE THREAD

**Issue by dollajas** [ThoreBor/Anki_Leaderboard#58]
seems to reset every new day, can anyone else confirm?

**Comment by ThoreBor** [comment]
Yes, that's on purpose. You only see people that synced on the same day as you. Do you have another suggestion?

**Comment by dollajas** [comment]
Having it update automatically? Or everytime the user logs into anki / syncs? I would like to be able to compare my progress to them without having to remind them to open the add-on every day

**Comment by ThoreBor** [comment]
That's not a bad idea. I could try to calculate the stats and sync them to the server when Anki is opend. Calculating and syncing does take some time though so I have to check if this causes some problems. But this gave me an idea how to fix #8 and #9  Thanks!

**Comment by khonkhortisan** [comment]
> I would like to be able to compare my progress to them without having to remind them to open the add-on every day

And similarly, I don't always feel like opening the leaderboard on any given day, but I still want to show up if someone else opens it.

**Comment by ThoreBor** [comment]
Yes, I'm working on it, but it would also only work with Anki 2.1.24+.  
I could start a background syncing thread when Anki starts, but I want to avoid having two syncing threads (the second one starts when the leaderboard is opened) at the same time.
