### ISSUE TITLE
Leaderboard causes Anki to freeze

### ISSUE THREAD

**Issue by ThanhLD24** [ThoreBor/Anki_Leaderboard#59]
**Describe the bug**
Once I press to the  Leaderboard menu, the Anki app will not be responding and I have to restart Anki to use again.

**Expected behavior**
I hope the Leaderboard feature will not make the Anki delay and Leaderboard should respond immediately once I call this function

**Screenshots**
![image](https://user-images.githubusercontent.com/15336708/79932208-267e2f80-8477-11ea-8310-2ce255ed9fe3.png)

**Info**
- Anki version: 2.1.22
- Leaderboard version: v1.4.3
- Start of new day: 4
- OS: Windows 10

**Comment by ThanhLD24** [comment]
I don't know how the reason, but now I try again, it responded after a few seconds.

**Comment by ThoreBor** [comment]
When you open the add-on three main things happen:
1. Your stats are being calculated
2. Your stats are being uploaded to the server
3. Leaderboard data is being downloaded and formatted into the Leaderboard you see

This can take a few seconds and if your internet connection is slow, or the server has to handle too many requests it could take even longer and might cause anki to freeze.

**Comment by ThanhLD24** [comment]
I agree with you, but about user experience aspect, this makes me feel uncomfortable, I don't know when the internet connection is low or server has to handle too many requests...., once the Anki not responding, I have to restart it to reuse, you know, It is the bad experience.
I have an idea, you should put the add-on run on other thread, not depend on main thread, if the leaderboard is loading data, it will show the loading popup and the user can press to cancel button if the process takes a long time.
I hope you improve this useful add-on. Thank you!

**Comment by ThoreBor** [comment]
I also have the problem, but I think the reason for that I'm using an old laptop (e.g. only 4gb ram). It would be interesting to know what you're specs are. Let me know if you regularly have this problem.
I'm not sure if that's what you mean, but threading causes some problems (see #9 ) .

**Comment by ThanhLD24** [comment]
This is my computer specs:
- CPU: I5 7400 / Ram: 12GB / HDD 1TB 7200rpm.
![image](https://user-images.githubusercontent.com/15336708/79972047-86002d80-84bf-11ea-9bec-512ddf46be5b.png)

> Let me know if you regularly have this problem

Yes, this afternoon, I got this problem once again, and now it works again.

> I'm not sure if that's what you mean
I mean, use the interface to report problem to the user instead make the app not responding, about the technical I don't know at all :D

**Comment by alexmehta** [comment]
I have the same issue. I guess it isn't really a bug but an annoying issue. Here are my specs: 
![image](https://user-images.githubusercontent.com/53285116/95137141-51ee9100-071c-11eb-8bd8-d15703b742fa.png)
I get this almost every time. I don't think my internet connection is an issue I have 300mbps.

**Comment by ThoreBor** [comment]
Thanks for reporting this. I'm now also thinking that it's probably not an internet connection issue. If it (or the server) is too slow you should get an error message that says so.  The specs likely don't matter that much either.
If I had to make a guess, I'd say it could have something to do with the way the stats are being calculated. For me at least, calculating them takes the most amount of time when opening the leaderboard. I'm pretty sure there has to be a more effective and faster way to calculate them, but for now, I can't think of one.  It would help to know how many reviews you did in total (all time) and what your streak currently is. Calculating the streak takes by far the longest. 
If this takes too long, Anki might freeze. That also happens to me occasionally, but only very briefly.

**Comment by MotaOcimar** [comment]
Same problem here.
I'm a Kubuntu user:
![image](https://user-images.githubusercontent.com/29007115/133253949-e56139b7-ad01-4294-8c76-434722fe1c13.png)

It also happens almost every time.

**Comment by ThoreBor** [comment]
In the next version freezing issues should be fixed finally
