### ISSUE TITLE
Automatic scroll/Country & Group

### ISSUE THREAD

**Issue by N8Dawwwg** [ThoreBor/Anki_Leaderboard#60]
**Describe the bug**
2 issues:
1. The first is that when the "automatic scroll to yourself" option is selected in config then the leaderboard app will open, but shows up black. (I've attached a screenshot so you can see what it looks like.) Removing the selection fixes the problem, but then you don't get the automatic scroll feature.
2. When I select the group/medical school Anki option or the country/United States the program doesn't rank me in those categories. I can see that others are ranked, even those that have not studied at all and have zeros across the board, but I still don't show up, even at the bottom. 

**Expected behavior**
1. I expected the program to automatically scroll to my name when I open it.
2. I expected to be ranked in the leaderboards in the appropriate section. 

**Screenshots**
<img width="580" alt="Screen Shot 2020-04-25 at 12 16 38 AM" src="https://user-images.githubusercontent.com/64300676/80272930-163e9e00-868b-11ea-8538-48cede0b5049.png">

<img width="580" alt="Screen Shot 2020-04-23 at 11 50 11 PM" src="https://user-images.githubusercontent.com/64300676/80272933-19398e80-868b-11ea-9ae1-9a96751a6321.png">

**Info**
- Anki version v2.1.23
- Leaderboard version v.1.4.3
- Start of new day 7 (I did toggle this between 4 and 7 and it made no difference)
- OS: Mac OS X 10.15.2

**Additional context**
I am running a few other add-ons and have attached a screenshot below. I understand that there is a possibility that one of them is interfering with your code.

**Comment by ThoreBor** [comment]
The first problem seems to be the same as #57 . This person also uses Mac and Anki 2.1.23 so that might be the problem. Officially I only support Anki 2.1.22 for now, as this is the newest version for windows.

The second issue should be fixed if you update the leaderboard to v1.4.3.1.

**Comment by N8Dawwwg** [comment]
Thank you!
