### ISSUE TITLE
leaderboard opens empty window

### ISSUE THREAD

**Issue by sc00bacat** [ThoreBor/Anki_Leaderboard#61]
**Describe the bug**
Shift+L and opening manually results in an empty leaderboard window screen

**Expected behavior**
leaderboard window opens with corresponding global/country/friends/group stats

**Screenshots**
![Screen Shot 2020-04-27 at 2 12 21 PM](https://user-images.githubusercontent.com/63348779/80405835-26c06580-8891-11ea-89cd-44f1a3b18d1b.png)

**Info**
- Anki version: 2.1.23
- Leaderboard version: 1.4.3.1
- Start of new day: 5
- OS: Mac

**Comment by ThoreBor** [comment]
Do you by any chance have "Scroll to yourself" enabled like #60 and #56 ?

**Comment by sc00bacat** [comment]
Yup; looks like the issue goes away when "Scroll to yourself" is disabled. Sorry about that, hadn't realized it was the same issue based on the title of their issues!

**Comment by ThoreBor** [comment]
No problem. Thank you for reporting it anyway. Look like it's either an anki 2.1.23 or mac issue.
