### ISSUE TITLE
Reviews after 12am not reported by add on

### ISSUE THREAD

**Issue by ExtremeCoolDude** [ThoreBor/Anki_Leaderboard#62]
**Describe the bug**
The addon doesn't register the reviews done after 12 am if the "next day starts"  is other than 0. ( i.e. if the system date is tomorrow but anki is still in yesterday due to next day starting at for eg. 7 am)

**Info**
- Anki version 2.1.23
- Leaderboard version - latest from ankiweb
- OS: mac

**Additional context**

**Comment by ThoreBor** [comment]
Sorry, I don't understand what the problem ist. Make sure that the new day of the leaderboard matches the configurations in Ankis preferences (the default is 4am). If the new day starts at 4am reviews before 4am are counted as yesterdays reviews.

**Comment by ExtremeCoolDude** [comment]
Current settings is 4 am which matches anki's preferences.

The reviews between 12am and 4am are not counted.

**Comment by ThoreBor** [comment]
Okay, so say you've done 300 reviews during the day and 50 after midnight, what does the leaderboard show? 300, or 0?

**Comment by ExtremeCoolDude** [comment]
Showing 300.

**Comment by ThoreBor** [comment]
And you're using Leaderboard v.1.4.3.1?

**Comment by ThoreBor** [comment]
And could you please send me a screenshot of all the addons you're using?

**Comment by ExtremeCoolDude** [comment]
Sorry for the delay, had to wait till 12 am. It's showing a new update, before I check that, the current version is v1.4.3.1

**Comment by ExtremeCoolDude** [comment]
![image](https://user-images.githubusercontent.com/50034073/80749346-07059780-8b46-11ea-8db4-de5d20fcde87.png)
![image](https://user-images.githubusercontent.com/50034073/80749398-1684e080-8b46-11ea-9e92-5be0bee6a1ac.png)

**Comment by ThoreBor** [comment]
Thanks, this should help narrow the issue down.

**Comment by ThoreBor** [comment]
Please let me know, if v1.4.5 fixed the issue.

**Comment by ExtremeCoolDude** [comment]
Fixed!
