### ISSUE TITLE
Option to export friends does not work

### ISSUE THREAD

**Issue by cjdduarte** [ThoreBor/Anki_Leaderboard#63]
**Describe the bug**

Option to export friends does not work.

![image](https://user-images.githubusercontent.com/42243532/80620957-09200700-8a1d-11ea-86d8-a8f6549d2ecc.png)

**Comment by ThoreBor** [comment]
Are you sure you checked the right folder? Go to Tools>Add-On>Leaderboard>View Files. The text file should be there. It's called 'Friends'.

**Comment by cjdduarte** [comment]
![image](https://user-images.githubusercontent.com/42243532/80704760-8b5f0880-8abb-11ea-9989-475045421f75.png)

**Comment by cjdduarte** [comment]
Sorry, it was an error in my English translation, resolved.
However, it is a suggestion that I can indicate another path when saving.
