### ISSUE TITLE
Cards completed number not matching leaderboard number

### ISSUE THREAD

**Issue by RT94** [ThoreBor/Anki_Leaderboard#65]
**Describe the bug**
The number of anki cards completed that is shown on the homescreen does not match what it says in the leaderboard. I have it set to start the next day at 5 hours past midnight in both my anki settings and the leaderboard, however it does not show an accurate number. It also stops counting any cards that I complete after 12 am midnight. These screenshots were taken around 2:30 am. I had completed around 200-250 cards after midnight, which as you can see were not counted.

**Screenshots**
![image](https://user-images.githubusercontent.com/64577185/80680319-88005880-8a8c-11ea-9342-e965e8f834c3.png)
![image](https://user-images.githubusercontent.com/64577185/80681095-fabe0380-8a8d-11ea-8c52-2b9b488ef0f5.png)
![image](https://user-images.githubusercontent.com/64577185/80680480-d877b600-8a8c-11ea-9dea-b734424dc354.png)
![image](https://user-images.githubusercontent.com/64577185/80680532-f0e7d080-8a8c-11ea-9840-bf2dfc2f98fd.png)
![image](https://user-images.githubusercontent.com/64577185/80680603-15dc4380-8a8d-11ea-9aa1-92416b0bb10c.png)
![image](https://user-images.githubusercontent.com/64577185/80680632-27255000-8a8d-11ea-9951-c1f4f76e8bb7.png)

**Info**
- Anki version: 2.1.22
- Leaderboard version: v1.4.4b
- Automatic scrolling is enabled and start time is 5 hours past midnight
- OS: Windows 10

**Comment by ThoreBor** [comment]
Are you the same person as the latest comment on [Ankiweb](https://ankiweb.net/shared/info/41708974)?

**Comment by ThoreBor** [comment]
If you want you can send me your anki collection. Then I can take a closer look at it.

**Comment by RT94** [comment]
Yes I am the same person. I attached my collection
[collection-2020-04-30@10-48-52.zip](https://github.com/ThoreBor/Anki_Leaderboard/files/4559045/collection-2020-04-30%4010-48-52.zip)

**Comment by ThoreBor** [comment]
Thank you. On my end the leaderboard score matches ankis stats. I'll try to figure something out.

**Comment by RT94** [comment]
Sounds good. Thanks for the timely responses. Much appreciated

**Comment by ThoreBor** [comment]
Could you check if this fixes the issue?

https://drive.google.com/open?id=1Nhlz8sh0oUtW0rnz6kasb-kDbsdM0E5t

**Comment by RT94** [comment]
I uninstalled the existing Leaderboard and installed the new file, but I cannot login at all now. I attached a screenshot of the error when logging in
![image](https://user-images.githubusercontent.com/64577185/80838543-47592a00-8bc7-11ea-9053-b4dc9782efdd.png)

**Comment by ThoreBor** [comment]
The server is experiencing some issues. Just try again. Let me know if the problem persists.

**Comment by RT94** [comment]
Ok just tried it again and it seems to be working. Does this also fix the issue where the cards are not counted after midnight?

**Comment by ThoreBor** [comment]
Yes, it should.

**Comment by RT94** [comment]
Ok great. I'll update you after midnight to confirm it's working. Thanks for the help. Much appreciated

**Comment by RT94** [comment]
So far so good. Everything seems to be working now. Thank you very much and I appreciate all of your time and help!

**Comment by ThoreBor** [comment]
Great, I'm happy to hear that.
