### ISSUE TITLE
Error with Anki 2.1.24 beta 9 (Leaderboard version 1.4.4 on Linux)

### ISSUE THREAD

**Issue by ghost** [ThoreBor/Anki_Leaderboard#67]
**Describe the bug**
An error screen appears while reviewing cards  but it is still possible to use Anki.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/61736804/80797258-51d1ee80-8bdc-11ea-9baa-287a55b25f89.png)

**Info**
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.24 (359b9f5c) Python 3.8.1 Qt 5.14.1 PyQt 5.14.1
Platform: Linux
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-04-30 22:50:09
Add-ons possibly involved: ⁨Leaderboard⁩

Exception in thread Thread-3028:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 1254, in run
  File "/home/m/.local/share/Anki2/addons21/41708974/Leaderboard.py", line 92, in load_leaderboard
    streak = data_list[1]
IndexError: list index out of range
Exception in threading.excepthook:
Exception ignored in thread started by: <bound method Thread._bootstrap of <Timer(Thread-3028, started 139717631137536)>>
Traceback (most recent call last):
  File "threading.py", line 890, in _bootstrap
  File "threading.py", line 934, in _bootstrap_inner
  File "threading.py", line 1212, in invoke_excepthook
AttributeError: 'ErrorHandler' object has no attribute 'flush'
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
AttributeError: 'ErrorHandler' object has no attribute 'flush'

**Additional context**
The add-on seems to be working but the error appears every 10-20 minutes while reviewing cards. Leaderboard version 1.4.4 (latest)

**Comment by ThoreBor** [comment]
Thanks for letting me know. Corrupted data in the leaderboard database could be the issue. I'll look into it.

**Comment by ThoreBor** [comment]
Do you still have the issue with the newest update?
