### ISSUE TITLE
True Retention percent

### ISSUE THREAD

**Issue by bushwhackermoore** [ThoreBor/Anki_Leaderboard#68]
I feel like I may be more motivated to get cards done instead of get them done accurately.

![image](https://user-images.githubusercontent.com/64649239/80814196-0ba36d80-8b91-11ea-8acd-9610c1c5cdd2.png)

Could you include a column that has percent correct of mature cards? As in the picture above, it could include a section of percent correct of mature cards.

**Comment by ThoreBor** [comment]
Someone made the same suggestion in #43 . I dismissed it at the time, but im reconsidering it now, because I agree that this could happen: 
> I feel like I may be more motivated to get cards done instead of get them done accurately.

**Comment by ThoreBor** [comment]
I added retention to v1.4.6.
