### ISSUE TITLE
Cannot open the leaderboard

### ISSUE THREAD

**Issue by JasjoL** [ThoreBor/Anki_Leaderboard#70]
Every time I try to open the leaderboard an error screen pops up.

The error message that I get is:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site.
Debug info:
Anki 2.1.21 (f1734a47) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.14.6
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-05-03 10:40:54
Add-ons possibly involved: Leaderboard

Caught exception:
Traceback (most recent call last):
File "/Users/jasonlin/Library/Application Support/Anki2/addons21/41708974/init.py", line 21, in Main
mw.leaderboard = start_main()
File "/Users/jasonlin/Library/Application Support/Anki2/addons21/41708974/Leaderboard.py", line 24, in init
self.setupUI()
File "/Users/jasonlin/Library/Application Support/Anki2/addons21/41708974/Leaderboard.py", line 50, in setupUI
self.load_leaderboard()
File "/Users/jasonlin/Library/Application Support/Anki2/addons21/41708974/Leaderboard.py", line 239, in load_leaderboard
self.dialog.Friends_Leaderboard.item(friend_counter-1, j).setBackground(QtGui.QColor("#51f564"))
AttributeError: 'NoneType' object has no attribute 'setBackground'

Screenshots

Steps to reproduce bug
If possible, step by step instructions for how to reproduce the bug

Info

Anki version: 2.1.21
Leaderboard version: v.1.4.5
MacOS

**Comment by JasjoL** [comment]
![image](https://user-images.githubusercontent.com/63017857/80919824-b81c5580-8d31-11ea-978a-41f68ba6af8a.png)

**Comment by ThoreBor** [comment]
Please send me the contents of meta.json. You can find it by going to Tools>Add-On>Leaderboard>View Files

**Comment by JasjoL** [comment]
{"name": "Leaderboard", "mod": 1588414263, "min_point_version": 0, "max_point_version": -23, "branch_index": 0, "config": {"new_user": "False", "username": "Jasjo", "friends": ["MSAyawar", "hiimnewusr", "tanman"], "newday": "4", "subject": "Medical School Anki", "country": "United States", "scroll": ""}, "disabled": false, "conflicts": []}

**Comment by ThoreBor** [comment]
Try to replace it with this:

{"name": "Leaderboard", "mod": 1588414263, "min_point_version": 0, "max_point_version": -23, "branch_index": 0, "config": {"new_user": "False", "username": "Jasjo", "friends": ["MSAyawar", "hiimnewusr", "tanman", "Jasjo"], "newday": "4", "subject": "Medical School Anki", "country": "United States", "scroll": ""}, "disabled": false, "conflicts": []}

**Comment by JasjoL** [comment]
damn thanks it worked! i guess i just needed to befriend myself haha

Appreciate the quick help!

**Comment by ThoreBor** [comment]
Great! Yes, this should happen by default though. Did you by any chance use the import friends function?

**Comment by JasjoL** [comment]
Nope, when the friend feature was first introduced i manually added my friends. I guess i removed my own name without knowing it. It's weird that I didn't get this issue until yesterday though

**Comment by ThoreBor** [comment]
You probably updated the add-on yesterday. Do you know which version you used before?

**Comment by JasjoL** [comment]
Yeah you're right I do remember updating the add-on yesterday. Sorry I don't remember the version but I thought i had been updating fairly frequently.

**Comment by sc00bacat** [comment]
I just had the same issue as JasjoL after the newest update. I do remember deleting myself as a friend because I thought it was odd that I was my own friend lol. But adding myself back into friends as explained earlier solved the issue!

**Comment by ThoreBor** [comment]
Alright, in the next version I'll change it, that you're username won't show up in the config friends list.
