### ISSUE TITLE
"Couldn't find friend"

### ISSUE THREAD

**Issue by pooner18** [ThoreBor/Anki_Leaderboard#72]
Unable to add new friends despite them indicating they have created an account and can add me. I currently have 4 friends - including myself. 

I have the latest version of Leaderboard.

**Comment by ThoreBor** [comment]
What's the username of your friend?

**Comment by pooner18** [comment]
antibodics95 and Nagz

Thanks!

**Comment by ThoreBor** [comment]
Those usernames are not in the database. Are you sure that they already created the accounts?

**Comment by Nagz93** [comment]
hi, Nagz here,
I created a user name through anki add-on (not the website) as Nagz, 
now I just created another account to be able to comment on this thread which is Nagz93 
please let me know if you can see either in your database

**Comment by ThoreBor** [comment]
I found the issue. Just open the Leaderboard and everything should be fixed. Afterwards @pooner18 
should be able to add you.
Accounts weren't properly created due to an issue I caused while updating something on the server.

**Comment by ThoreBor** [comment]
![image](https://user-images.githubusercontent.com/40232329/81104513-ea38dd80-8f12-11ea-8c27-c2d96b087fe5.png)
 Looks like it worked

**Comment by pooner18** [comment]
Much appreciated - it worked! Could you also apply the fix to my buddy antibodics95?

**Comment by ThoreBor** [comment]
It should be fixed for all accounts. He just has to reopen the leaderboard so his data gets synced.
