### ISSUE TITLE
Sorting leaves white rows in night mode

### ISSUE THREAD

**Issue by zjosua** [ThoreBor/Anki_Leaderboard#74]
**Describe the bug**
When changing the sorting column in night mode, previously highlighted rows become white.

**Screenshots**
![image](https://user-images.githubusercontent.com/5960563/81448497-bf52c180-917e-11ea-9fb7-53f976b4de88.png)

**Steps to reproduce bug**
Start Anki with night mode enabled. Change sorting order in Leaderboard.

**Info**
- Anki version 2.1.26
- Leaderboard version v1.4.6
- OS: Debian bullseye

**Additional context**
https://github.com/ThoreBor/Anki_Leaderboard/blob/master/Leaderboard.py#L476
Anki uses #3A3A3A (uneven rows) and #2F2F31 (even rows) in night mode.

**Comment by ThoreBor** [comment]
Should be fixed now. Also made sure that even and odd rows in day mode have alternating row colors.
