### ISSUE TITLE
It would be nice to see yesterdays leaderboard.

### ISSUE THREAD

**Issue by Venom21G** [ThoreBor/Anki_Leaderboard#75]
**Is your feature request related to a problem? Please describe.**
it would be great if we could see yesterdays leaderboard in addon.

**Describe the solution you'd like**
Yesterdays leaderboard in separate tab.

**Comment by ThoreBor** [comment]
I like the idea, but that's not possible with the current database.  I only store the most recently synced data from each user, so everyone that synced their data today wouldn't show up in yesterdays leaderboard. 
I'll keep this in mind, though.

**Comment by ThoreBor** [comment]
I'll close this and use #144 to address this.
