### ISSUE TITLE
Change UI to show 'Friends' first when opening leaderboard!

### ISSUE THREAD

**Issue by topgun2990** [ThoreBor/Anki_Leaderboard#78]
If you could configure the UI to show Friends **first** (instead of 'Global') or provide a way for us to choose which leaderboard we want to see first when opening add-on, that would be great! Thank you!!

**Comment by ThoreBor** [comment]
Good idea! I'll include it in the next update (probably later today or tomorrow).

**Comment by topgun2990** [comment]
Thanks!
