### ISSUE TITLE
Crete new group Concursos

### ISSUE THREAD

**Issue by antonio-victor** [ThoreBor/Anki_Leaderboard#79]
Is it possible to create a group called "Concursos" on Leaderboard add-on? Couldn't find how, so I'm guessing that is not possible yet, right? Is it possible for Developers to add this group?

**Comment by ThoreBor** [comment]
I'll officially add it in the next update, but you can already download the changed version here from github.

**Comment by antonio-victor** [comment]
@ThoreBor Awesome! Thank you!
