### ISSUE TITLE
Question: Is it possible to have a filter or user-specific URL on the website?

### ISSUE THREAD

**Issue by topgun2990** [ThoreBor/Anki_Leaderboard#81]
On the website for the addon, other than simply running a CTRL-F for our user name on the global list, is there a way to filter the list or view a user-specific URL that shows only our daily stats? (The purpose for this would be if we want someone to be able to check up on us and hold us accountable on a mobile device when they can't open Anki on a computer or if they aren't an Anki user, for example.)

Example:
https://ankileaderboard.pythonanywhere.com/user-"usernamexx"

Strange request, I know. But thanks!

**Comment by ThoreBor** [comment]
Sure! Something like this? https://ankileaderboard.pythonanywhere.com/user/topgun2990/
You can also just click on the username on the leaderboard and you'll get redirected to this site.

**Comment by topgun2990** [comment]
Oh, whoops, haha. Should have just tried clicking. Thanks!

**Comment by topgun2990** [comment]
Oh, one thing I noticed-- Instead of it saying "streak" it says "steak" on the user specific screen.

**Comment by ThoreBor** [comment]
My bad, just fixed it!
