### ISSUE TITLE
Error - Invalid Token

### ISSUE THREAD

**Issue by spartandrew18** [ThoreBor/Anki_Leaderboard#84]
**Describe the bug**
When I click The leaderboard menu it opens a box saying "Error - invalid token" This just started happening when I updated it today.

**Screenshots**
![image](https://user-images.githubusercontent.com/66539077/84710921-2b210a80-af33-11ea-955e-91e906ff551a.png)

**Info**
- Anki version 2.1.26
- Leaderboard version 1.5.1
- If relevant Add-on config info (start of new day, autoscrolling enabled etc.)
- OS: Windows 10

**Additional context**

**Comment by ThoreBor** [comment]
I think I temporarily fixed it now. 

Just to make sure, please open the debug console (Ctrl+Shift+;)  enter `print(mw.col.conf.get('Leaderboard_Token'))` and press Ctrl+Return. Please let me know if the output isn't a string of 40 random characters. **Don't tell me what the token is**

Did you by any chance use the sync only function (Shift+S, or Leaderboard>Sync) before opening the Leaderboard after updating the add-on?

**Comment by ThoreBor** [comment]
I just noticed another issue. There seems to be a problem with syncing the token across different devices. I disabled the verification for now.

**Comment by ThoreBor** [comment]
On my end, everything is working again, but I'll keep monitoring the server logs. Please let me know if you still get the error.
