### ISSUE TITLE
Minutes Today is alway 0

### ISSUE THREAD

**Issue by antonio-victor** [ThoreBor/Anki_Leaderboard#85]
**Describe the bug**
After the update, my "Minutes Today" is alway 0 even Anki saying I've studied 2.41 hours. I looked in the Leaderboard and many users has the same bug. It shows "Reviews Today" with the right number of reviews, but the "Minutes today" is empty.

**Screenshots**
![minutes today](https://user-images.githubusercontent.com/16549329/84894214-d1295d80-b076-11ea-8714-a6bd20a9ba9c.jpg)

**Steps to reproduce bug**
-

**Info**
    
    Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=True sv=1
    Add-ons, last update check: 2020-06-17 06:00:57
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Edit Field During Review ['1020366288', 2020-01-29T13:33, 'None', '']
    Leaderboard ['41708974', 2020-06-15T14:36, 'None', mod]
    More Overview Stats 21 ['738807903', 2020-03-22T13:40, 'None', '']
    Progress Graphs and Stats for Learned and Matured Cards ['266436365',                                           2020-03-29T03:26, 'None', '']
    True Retention ['613684242', 2020-03-22T13:38, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1020366288 266436365 41708974 613684242 738807903
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

Anki Leaderboard v1.5.1
Windows 10

**Additional context**
It was working okay before the update.

**Comment by ThoreBor** [comment]
Thanks for letting me know. I removed a few things in the stats.py that I thought aren't necessary, but apparently they are (everything was working fine for me though).
I just uploaded a fix so everything should be working again.

**Comment by antonio-victor** [comment]
Thank you @ThoreBor ! You're the best
