### ISSUE TITLE
Group suggestion: ENEM/Vestibular

### ISSUE THREAD

**Issue by Vitorvlv** [ThoreBor/Anki_Leaderboard#87]
hey, I don't know how specific you want to get with the groups, but would it be possible for you to add ENEM/Vestibular as an option on the groups tab?

ENEM/Vestibular are the exams needed to get into college in Brazil, it would be nice to have that as an option. 

Thanks!

**Comment by NameLessGO** [comment]
Too be fair it is basically a Concurso 
ENEM/Vestibular is the **exam** to pass high school, i think is called SAT,MCAT(idk)
Concurso is a **exam** to get a job or a public career 
The more you know.

**Comment by ThoreBor** [comment]
Sure, I'll add it in the next update!

**Comment by Vitorvlv** [comment]
Thank you!

**Comment by ThoreBor** [comment]
Just to make sure: Do you want me to add _ENEM/Vestibular_, or _ENEM_ **and** _Vestibular_, or just one of them?

**Comment by Vitorvlv** [comment]
ENEM/Vestibular is fine, thank you!
