### ISSUE TITLE
can't delete leaderboard account

### ISSUE THREAD

**Issue by 123buzz** [ThoreBor/Anki_Leaderboard#88]
**Describe the bug**
Made an account for the MCAT leaderboard group. Tried deleting the account but it keeps saying "Error." 

**Screenshots**
<img width="481" alt="image" src="https://user-images.githubusercontent.com/67342732/85457199-c33f7500-b56d-11ea-868c-726d3523e4c1.png">

**Steps to reproduce bug**
I go to add-ons, click Leaderboard, click config, type in my username, click delete account, and then it says Error in a box on the bottom left corner.

**Info**
- Anki version (Help>About; e.g. 2.1.26)
- Leaderboard version (Leaderboard>Config>About tab; e.g. v.1.4.4)
- If relevant Add-on config info (start of new day, autoscrolling enabled etc.)
- OS: macOS Catalina

**Additional context**
If it's possible, please delete the account with the username bemeed. I've tried doing so and I keep getting the error message.

**Comment by ThoreBor** [comment]
What version of the add-on are you using? Is there a file called Leaderboard_Token.txt in your collection.media folder?
