### ISSUE TITLE
Update other people's scores without having to close it first [optional enhancement]

### ISSUE THREAD

**Issue by khonkhortisan** [ThoreBor/Anki_Leaderboard#9]
Depends on https://github.com/ThoreBor/Anki_Leaderboard/issues/7
Do no earlier than https://github.com/ThoreBor/Anki_Leaderboard/issues/8
Update the scoreboard when going to the decks list or every x minutes or some other sane default

**Comment by ThoreBor** [comment]
Putting `threading.Timer(60.0, self.sync).start()` in the sync function would work for updating the score of other people, but syncing, and updating your own (#8 ) throws this error when calling `Stats()`, and I don't know what to do about it:

> Debug info:
> Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
> Platform: Windows 10
> Flags: frz=True ao=True sv=2
> Add-ons, last update check: 2020-04-09 15:31:40
> 
> Exception in thread Thread-25:
> Traceback (most recent call last):
>   File "threading.py", line 932, in _bootstrap_inner
>   File "threading.py", line 1254, in run
>   File "C:\Users\Thore Tyborski\AppData\Roaming\Anki2\addons21\41708974\Leaderboard.py", line 62, in sync
>     streak, cards, time, cards_past_30_days = Stats()
>   File "C:\Users\Thore Tyborski\AppData\Roaming\Anki2\addons21\41708974\Stats.py", line 13, in Stats
>     reviews = mw.col.db.list("SELECT id FROM revlog")
>   File "lib\site-packages\anki\db.py", line 81, in list
>   File "C:\Users\Thore Tyborski\AppData\Roaming\Anki2\addons21\403491806\__init__.py", line 23, in myExecute
>     return oldExecute(self, sql, *a, **kw)
>   File "lib\site-packages\anki\db.py", line 33, in execute
> sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 13612 and this is thread id 10456.
> Exception in threading.excepthook:
> Exception ignored in thread started by: <bound method Thread._bootstrap of <Timer(Thread-25, started 10456)>>
> Traceback (most recent call last):
>   File "threading.py", line 890, in _bootstrap
>   File "threading.py", line 934, in _bootstrap_inner
>   File "threading.py", line 1212, in invoke_excepthook
> AttributeError: 'ErrorHandler' object has no attribute 'flush'
> Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
> AttributeError: 'ErrorHandler' object has no attribute 'flush'

**Comment by khonkhortisan** [comment]
`SQLite objects created in a thread can only be used in that same thread.` is from **running .list() in a new thread**. Not from review =, not from mentioning mw.col.db, not from accessing it inside Stats() instead of sync() directly. Running `threading.Timer(0, self.sync).start()` once from SetupUI doesn't help. I tried check_same_thread=False, .commit(), and .close().

Here's a suggestion for how to maybe get around that:
Have separate `downloadsync` and `uploadsync` functions.
When opening the leaderboard, create the blank leaderboard window, start a thread for `downloadsync`, run `uploadsync`, and return.
When exiting the reviewer or when answering a card or after having answered x cards, run `uploadsync`.
`downloadsync` fills in the leaderboard window and runs in a while loop with a sleep timer, and exits if the leaderboard doesn't exist/was closed.
`uploadsync` reads the database, updates the user's info on the leaderboard window, and uploads the user's info.

**Comment by ThoreBor** [comment]
That's a good idea. I'll try that. Thank you.

**Comment by ThoreBor** [comment]
It looks like we got lucky. I just noticed that Anki 2.1.24 solves this problem. From the [change log](https://changes.ankiweb.net/#/):
> The database is now behind a mutex, and can be safely accessed from a background thread.

So this fixes this issue and #8 . I'm going to test it a bit more and make some changes.
