### ISSUE TITLE
Anki keeps Crashing

### ISSUE THREAD

**Issue by djsmitty** [ThoreBor/Anki_Leaderboard#92]
Ever since I've downloaded this my Anki will just randomly crash which causes me to lose any progress I haven't saved.

**Comment by ThoreBor** [comment]
I need more information than that to understand what the issue might be:
What Anki version are you using and what OS? What add-on version are you using? Does Anki just crash, or does it freeze and then crash? Do you get any error messages? Does everything work normally when you disable the add-on? When/how often does it crash?

**Comment by djsmitty** [comment]
I'm on Anki 2.1.26 and I got the add on yesterday so it's the most recent one. If I don't open the leaderboard Anki won't crash, but if I have it open in the background it will just randomly close and I will get a message saying "Anki unexpectedly crashed". Everything works like normal without the add on. If I have the leaderboard open it crashes after like 10-20 mins.

**Comment by djsmitty** [comment]
<img width="519" alt="Screen Shot 2020-07-08 at 12 29 54 PM" src="https://user-images.githubusercontent.com/67977694/86961851-c5c9cf00-c116-11ea-91c9-5d7663017bcf.png">

**Comment by ThoreBor** [comment]
Okay, thanks. Did you enable 'Refresh the Leaderboard every two minutes' in the config? If so, this might be related to issue #76

**Comment by djsmitty** [comment]
I did have that checked, I just changed that and I'll see if it stops.

**Comment by ThoreBor** [comment]
Any updates?
