### ISSUE TITLE
Can't Delete Account + Invalid Token

### ISSUE THREAD

**Issue by nmeed** [ThoreBor/Anki_Leaderboard#94]
I deleted my old setup and on my new one, I keep getting an "invalid token error," and obviously I no longer have my old meta.json file. As such, I tried to just delete my account to start from scratch. Unfortunately, I can't delete it either, it just says error. I also get an error when Anki is open, please see screenshot. 

Update: So all of this goes away if I make a new account... can you delete my old account ""?
Thanks.

**Steps to reproduce bug**
Delete Anki setup, sign in on new setup, open leaderboard... 
Delete Anki setup, sign in on new setup, try to delete account...

**Info**
- Anki version 2.1.26
- Leaderboard version 1.5.4
- If relevant Add-on config info (start of new day, autoscrolling enabled etc.)
- Mac 10.15.6

**Additional context**

**Comment by ThoreBor** [comment]
I reset the token of your account so you can keep using it if you want, or delete it.

**Comment by nmeed** [comment]
Thank you so very much!
