### ISSUE TITLE
How do I add a new group?

### ISSUE THREAD

**Issue by drdean794** [ThoreBor/Anki_Leaderboard#95]
Hello,

Is it possible to add a group to the list of existing groups? Is this not an option yet? I'd like to add my medical school as a group.

**Comment by ThoreBor** [comment]
At the moment I have to add groups manually, but since you're not the first person to ask I'll probably add an option that lets you create groups in the next update.  If you tell me what the group should be called, it'll definitely be included in the next update.

**Comment by drdean794** [comment]
MUCOM would be the name of the group! Thanks!

**Comment by drdean794** [comment]
Do updates automatically update? Or do we have to re-download the add on each time? Sorry, stupid question probably haha.

**Comment by ThoreBor** [comment]
Up until now, you had to re-download the add-on to see the newest groups. But with the upcoming update, you won't have to. You'll be able to create groups from the config and see new groups as soon as they are created. 
I just committed the changes to GitHub so you can download it from here if you already want to use it. I already included MUCOM.
I'll probably release the new version on AnkiWeb in the next week or so.
