### ISSUE TITLE
Login doesn't require password?

### ISSUE THREAD

**Issue by drdean794** [ThoreBor/Anki_Leaderboard#96]
Can we make it so that login requires password? Otherwise, anyone can login using any username.

**Comment by ThoreBor** [comment]
I really don't want to deal with hashing and storing passwords at the moment. But instead, the add-on creates a random token (40 character SHA-1 hash) and syncs it. If the token doesn't match the one in the database, you can't sync your data. For the record, you currently can "log in" in the config using any username, but all this does is change the username that is going to be synced and doesn't give you access to anything. It's only locally.

**Comment by drdean794** [comment]
Awesome thanks for the quick response man! Okay, so people can’t just my username in the config and then change what it says on the leaderboard stats?

**Comment by ThoreBor** [comment]
Yes, correct. But only if you use v1.5.4.
