### ISSUE TITLE
cant make an Account

### ISSUE THREAD

**Issue by Sallaloz** [ThoreBor/Anki_Leaderboard#99]
**Describe the bug**
cant make an Account. when I try to I get "Timeout error - No internet connection, or server response took too long". using Mac OS and updated everything but still not working.

**Screenshots**
![117703885_312848070157945_8230414776649191196_n](https://user-images.githubusercontent.com/70067568/90959912-7cef8f00-e4a6-11ea-866e-9a52cde33b94.png)

**Steps to reproduce bug**
If possible, step by step instructions for how to reproduce the bug

**Info**
- Anki version 2.1.3
- Leaderboard version 1.5.4
- OS: Mac

**Comment by ThoreBor** [comment]
Okay, great. But if everything else is working properly it probably has nothing to do with your internet provider. Maybe it's your firewall or something.

**Comment by Sallaloz** [comment]
I cant open the link on my phone using the Wifi as well. so I think that confirms it.
